"""
    SampleCratePyO3Only

A Julia package with the Rust crate `deps/sample_crate_pyo3_only` embedded in
it: a crate **written for PyO3 only**, with no `pub` anywhere and nothing
RustCall-specific. It is a real extension module (`crate-type = ["cdylib"]`,
pyo3's `extension-module`).

RustCall binds it as is (#424): `@rust_crate ... pyo3_host=true` builds the
crate **as the Python extension it already is** and calls the imported module.
That reaches what the C-ABI wrapper path cannot — the private `#[pyfunction]`s
an outside crate could not name (E0603), and `Python<'_>`/`Py<T>`/numpy/callable
signatures that need a live interpreter. PythonCall owns the interpreter, the
value bridge and object lifetime, so the crate must be registered in its
`#[pymodule]` for Julia to see it.

The two halves live in separate files:

- **Rust**: `deps/sample_crate_pyo3_only/src/lib.rs` — `#[pyfunction]`,
  `#[pyclass]`, `#[pymethods]` and nothing else. No Julia file contains Rust
  source, and no Rust file mentions Julia.
- **Julia**: this file. The bindings are generated by `@rust_crate` below.

The build happens the first time a binding is called, not while this package is
precompiled: a Python interpreter may not be started during precompilation.

Every exported name here is the Julia binding of the same-named PyO3 item,
except `parse_int` and `distance`, which are Julia-side conveniences.
"""
module SampleCratePyO3Only

using RustCall
using RustCall: RustResult, is_ok, unwrap
# Loads PythonCall, and with it the `RustCallPyO3HostExt` extension that gives
# RustCall's host path its interpreter.
import PythonCall

# The host path: build `deps/sample_crate_pyo3_only` as the Python extension it
# is, import it, and define the typed bindings as `SampleCratePyO3Only.Bindings`.
@rust_crate joinpath(@__DIR__, "..", "deps", "sample_crate_pyo3_only") submodule="Bindings" pyo3_host=true

# Explicit list: exactly the names this module re-exports unchanged. The
# crate's `parse` is *not* among them — re-exporting it would shadow
# `Base.parse` for every user of this package — so it is reached as
# `Bindings.parse` by the `parse_int` wrapper below.
using .Bindings: add, shout,
                 Point, origin, norm, translate, label, scaled

# Names the PyO3 crate exposes, re-exported unchanged: `#[pyfunction]`s ...
export add, shout
# ... and the `#[pyclass]` with its `#[new]`, `#[staticmethod]` and methods.
export Point, origin, norm, translate, label, scaled

# Julia-side conveniences defined below.
export parse_int, distance

"""
    parse_int(s::AbstractString) -> Int32

Parse an integer in Rust through the crate's `parse`, a `#[pyfunction]`
returning `PyResult<i32>`. On the host path the interpreter renders the error,
so `Bindings.parse` returns a `RustResult{Int32, String}` whose `Err` payload is
the real `PyValueError` message; this wrapper turns any `Err` into an
`ArgumentError` naming the input.
"""
function parse_int(s::AbstractString)::Int32
    r = Bindings.parse(String(s))
    is_ok(r) || throw(ArgumentError("parse_int: not an integer: $(repr(s))"))
    return unwrap(r)
end

"""
    distance(p::Point, q::Point) -> Float64

Euclidean distance between two points, computed from the fields
`#[pyclass(get_all, set_all)]` exposes (`p.x`, `p.y` go through the Python
object) and the crate's `Point::norm`.
"""
function distance(p::Point, q::Point)::Float64
    d = Point(p.x - q.x, p.y - q.y)
    return norm(d)
end

end # module SampleCratePyO3Only
