"""
    emit_crate_module_code(info::CrateInfo, lib_path::String; kwargs...) -> String

Generate Julia module code as a string, suitable for writing to a file.

# Arguments
- `info::CrateInfo`: Crate information from scan_crate
- `lib_path::String`: Path to the compiled shared library (or relative path)

# Keyword Arguments
- `module_name::Union{String, Nothing}`: Name for the module
- `use_relative_path::Bool`: If true, treat lib_path as relative to @__DIR__
- `strict::Symbol`: how an unsupported return type is handled, see
  [`FFI_STRICT`](@ref). Threaded through every emitter rather than set globally,
  so concurrent calls do not interfere.
- `preload::Vector{String}`: libraries the image imports by name that the
  loader would not find on its own (a PyO3 wrapper's Python DLL on Windows),
  opened before it by `load_artifact!`. Emitted only when non-empty, so a file
  that needs none reads under a RustCall without the option.

# Returns
- `String`: Julia source code for the module
"""
function emit_crate_module_code(info::CrateInfo, lib_path::String;
    module_name::Union{String, Nothing} = nothing,
    use_relative_path::Bool = false,
    build_release::Bool = true,
    strict::Symbol = _ffi_strict(),
    lib_name::Union{String, Nothing} = nothing,
    preload::Vector{String} = String[],
    pin_library::Bool = false,
    python::Bool = false,
    build_options::NamedTuple = crate_build_options(release = build_release),
    build_record::Union{Nothing, CrateBuildRecord} = nothing,
    snapshot::Union{Nothing, BuildEnvSnapshot} = nothing
)
    # As `emit_crate_module`: the build's snapshot, or one of its own (#481).
    snapshot === nothing && (snapshot = BuildEnvSnapshot())
    # Determine module name
    mod_name = if module_name !== nothing
        module_name
    else
        snake_to_pascal(info.name)
    end

    lines = String[]

    # Header comment. The format marker is the `MAJOR.MINOR` of this release
    # (`BINDINGS_FORMAT_VERSION`, #489); the module checks it again below, so a
    # RustCall of another `MAJOR.MINOR` refuses the file instead of loading it.
    push!(lines, "# Auto-generated bindings for $(info.name)")
    push!(lines, "# Generated by RustCall.jl - DO NOT EDIT")
    push!(lines, "# Bindings format: $(BINDINGS_FORMAT_VERSION)")
    push!(lines, "# Regenerate with: write_bindings_to_file(\"$(info.path)\", \"<output_path>\")")
    push!(lines, "")

    # Module start
    push!(lines, "module $mod_name")
    push!(lines, "")

    # The only names this file gives Base and RustCall: aliases no Rust item
    # can be bound under (#528). Every reference below goes through them, so a
    # crate item named `Base`, `RustCall` or `getfield` shadows nothing the
    # wrappers use. `Libdl` is reached through RustCall, as the in-memory
    # module does (#339): a written file is loaded into the user's project,
    # which need not have `Libdl` among its dependencies (#461).
    push!(lines, "# Base and RustCall under names no Rust item can take (#528).")
    append!(lines, _emitted_aliases_source())
    push!(lines, "")
    push!(lines, "# Refused by a RustCall of another MAJOR.MINOR: regenerate the file (#489).")
    push!(lines, "const _BINDINGS_FORMAT = rustcall′RustCall.check_bindings_format($(repr(BINDINGS_FORMAT_VERSION)))")
    push!(lines, "")

    # Library path constant
    if use_relative_path
        # Through the alias, like every other name the file takes from Base: a
        # crate's `fn joinpath` is bound in this module too (#528 review).
        push!(lines, "const _LIB_PATH = rustcall′Base.joinpath(@__DIR__, $(repr(lib_path)))")
    else
        push!(lines, "const _LIB_PATH = $(repr(lib_path))")
    end
    # Every input of this build as one record, the value the expression
    # emitter splices, from the same call (`crate_build_record`, #474): what a
    # hot reload rebuilds from, and the registry name.
    record_name = lib_name === nothing ?
        crate_library_name(info; release = build_release, snapshot = snapshot) : lib_name
    build_record = something(build_record,
        crate_build_record(info.path, record_name; build_options = build_options,
                           python = python, snapshot = snapshot))
    build_record.lib_name == record_name || throw(ArgumentError(
        "the build record names `$(build_record.lib_name)`, not `$(record_name)`"))
    # `repr` spells the record `RustCall.CrateBuildRecord(...)`; the file names
    # RustCall only through its alias (#528).
    push!(lines, "const _BUILD_RECORD = rustcall′" * repr(build_record))
    push!(lines, "const _LIB_NAME = _BUILD_RECORD.lib_name")
    if !isempty(preload)
        push!(lines, "# Libraries the image imports by name that the loader would not find on")
        push!(lines, "# its own (a PyO3 wrapper's Python DLL on Windows, which has no rpath),")
        push!(lines, "# opened before it.")
        push!(lines, "const _PRELOAD_LIBRARIES = $(repr(Tuple(preload)))")
    end
    push!(lines, "const _PIN_LIBRARY = $(repr(pin_library))")
    push!(lines, "")
    push!(lines, "# Everything this module knows about the image it calls -- handle, liveness")
    push!(lines, "# flag and generation -- as one immutable value, published by the loader in")
    push!(lines, "# the transaction that swaps the registry entry (#277).")
    push!(lines, "const _LIB_GEN = rustcall′RustCall.StateView(:crate_generation, @__MODULE__)")
    push!(lines, "")
    push!(lines, "function __init__()")
    push!(lines, "    # Register before loading, and do not assign afterwards: an assignment")
    push!(lines, "    # after `load_artifact!` would overwrite a newer generation that a")
    push!(lines, "    # concurrent reload had already published. The prologue is the in-memory")
    push!(lines, "    # module's, statement for statement (`_crate_init_prologue`): the build")
    push!(lines, "    # environment is checked against `_BUILD_RECORD` first (#474).")
    for statement in _crate_init_prologue(:bindings_file)
        push!(lines, "    " * _emitted_source(statement))
    end
    push!(lines, "    # A private generation copy, never `_LIB_PATH` itself: that file is")
    push!(lines, "    # Cargo's output (or the copy `write_bindings_to_file` made of it), and")
    push!(lines, "    # an image mapped in place cannot be overwritten on Windows -- the next")
    push!(lines, "    # `cargo build` of the crate, and the next regeneration, would fail")
    push!(lines, "    # (#309). The in-memory `@rust_crate` path does the same.")
    push!(lines, "    rustcall_process_image = rustcall′RustCall.loadable_library_copy(_LIB_PATH)")
    push!(lines, "    _PIN_LIBRARY && rustcall′RustCall.preload_dependency!(rustcall′RustCall.crate_direct_policy(), rustcall_process_image)")
    push!(lines, "    rustcall′RustCall.load_artifact!(rustcall′RustCall.crate_direct_policy(), rustcall_process_image;")
    if isempty(preload)
        push!(lines, "                            lib_name = _LIB_NAME)")
    else
        push!(lines, "                            lib_name = _LIB_NAME, preload = _PRELOAD_LIBRARIES)")
    end
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "# Resolved symbols, memoized per handle: a reload swaps the image under the")
    push!(lines, "# same module. Negative answers are cached too.")
    push!(lines, "const _SYMBOLS = rustcall′RustCall.StateView(:crate_symbols, @__MODULE__)")
    push!(lines, "")
    push!(lines, "# Declared `::Ptr{Cvoid}`: the memo is a StateView and hands back an `Any`,")
    push!(lines, "# and an untyped symbol would box every snapshot element below.")
    push!(lines, "function _symbol(handle::rustcall′Base.Ptr{rustcall′Base.Cvoid}, name::rustcall′Base.String)::rustcall′Base.Ptr{rustcall′Base.Cvoid}")
    push!(lines, "    get!(_SYMBOLS, (handle, name)) do")
    push!(lines, "        ptr = rustcall′RustCall.Libdl.dlsym(handle, name; throw_error = false)")
    push!(lines, "        ptr === rustcall′Base.nothing ? rustcall′Base.C_NULL : ptr")
    push!(lines, "    end")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "function _required_symbol(handle::rustcall′Base.Ptr{rustcall′Base.Cvoid}, name::rustcall′Base.String)::rustcall′Base.Ptr{rustcall′Base.Cvoid}")
    push!(lines, "    ptr = _symbol(handle, name)")
    push!(lines, "    ptr == rustcall′Base.C_NULL && rustcall′Base.error(\"The Rust library '\" * _LIB_NAME *")
    push!(lines, "                           \"' does not export '\" * name * \"'.\")")
    push!(lines, "    ptr")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "function _live_handle(gen::rustcall′RustCall.CrateGeneration)")
    push!(lines, "    gen.handle == rustcall′Base.C_NULL &&")
    push!(lines, "        rustcall′Base.error(\"The Rust library backing this module is not loaded. \" *")
    push!(lines, "              \"It was either never initialised, or unloaded with \" *")
    push!(lines, "              \"RustCall.unload_library(\\\"\" * _LIB_NAME * \"\\\").\")")
    push!(lines, "    gen.handle")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "_get_func_ptr(name::rustcall′Base.String) = _required_symbol(_live_handle(_LIB_GEN[]), name)")
    push!(lines, "")
    push!(lines, "# What each arm below yields, named once so the cached answer and the")
    push!(lines, "# freshly resolved one cannot disagree about its shape.")
    push!(lines, "const _CALL_TARGET = rustcall′Base.Tuple{rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}}")
    push!(lines, "const _STRING_TARGET = rustcall′Base.Tuple{rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}}")
    push!(lines, "const _VEC_TARGET = rustcall′Base.Tuple{rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.RefValue{rustcall′Base.Bool}}")
    push!(lines, "const _CTOR_TARGET = rustcall′Base.Tuple{rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.RefValue{rustcall′Base.Bool}, rustcall′Base.Ptr{rustcall′Base.Cvoid}}")
    push!(lines, "const _FREE_TARGET = rustcall′Base.Tuple{rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′Base.RefValue{rustcall′Base.Bool}, rustcall′Base.Ptr{rustcall′Base.Cvoid}}")
    push!(lines, "")
    push!(lines, "# One snapshot per call, from ONE deref of `_LIB_GEN` (#277). `cache` is")
    push!(lines, "# the call site's own cache: the snapshot is kept in it and handed back")
    push!(lines, "# whole while the artifact epoch and the session token say it is still")
    push!(lines, "# this process's current answer (#253). A hit returns the very tuple one")
    push!(lines, "# deref produced, so nothing is ever reassembled from pieces.")
    push!(lines, "function _call_target(cache::rustcall′RustCall.CrateTargetCache, symbol::rustcall′Base.String)")
    push!(lines, "    hit = rustcall′RustCall.crate_target_hit(cache, _CALL_TARGET)")
    push!(lines, "    hit === rustcall′Base.nothing || return hit")
    push!(lines, "    # Sampled BEFORE the snapshot: a state write landing in between leaves")
    push!(lines, "    # this entry stamped with the older epoch and it is resolved again.")
    push!(lines, "    epoch = rustcall′RustCall.artifact_epoch()")
    push!(lines, "    handle = _live_handle(_LIB_GEN[])")
    push!(lines, "    return rustcall′RustCall.publish_crate_target!(cache, epoch,")
    push!(lines, "        (_required_symbol(handle, symbol),")
    push!(lines, "         _symbol(handle, rustcall′RustCall.ffi_panic_symbol(symbol))))")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "# ...and the owned-`String` arm, release function included.")
    push!(lines, "function _call_target(cache::rustcall′RustCall.CrateTargetCache, symbol::rustcall′Base.String, free_symbol::rustcall′Base.String)")
    push!(lines, "    hit = rustcall′RustCall.crate_target_hit(cache, _STRING_TARGET)")
    push!(lines, "    hit === rustcall′Base.nothing || return hit")
    push!(lines, "    epoch = rustcall′RustCall.artifact_epoch()")
    push!(lines, "    handle = _live_handle(_LIB_GEN[])")
    push!(lines, "    return rustcall′RustCall.publish_crate_target!(cache, epoch,")
    push!(lines, "        (_required_symbol(handle, symbol),")
    push!(lines, "         _symbol(handle, rustcall′RustCall.ffi_panic_symbol(symbol)),")
    push!(lines, "         _required_symbol(handle, free_symbol)))")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "# Owned Vec getter and release export from one generation (#303).")
    push!(lines, "function _vec_target(cache::rustcall′RustCall.CrateTargetCache, symbol::rustcall′Base.String, free_symbol::rustcall′Base.String)")
    push!(lines, "    hit = rustcall′RustCall.crate_target_hit(cache, _VEC_TARGET)")
    push!(lines, "    hit === rustcall′Base.nothing || return hit")
    push!(lines, "    epoch = rustcall′RustCall.artifact_epoch()")
    push!(lines, "    gen = _LIB_GEN[]")
    push!(lines, "    handle = _live_handle(gen)")
    push!(lines, "    return rustcall′RustCall.publish_crate_target!(cache, epoch,")
    push!(lines, "        (_required_symbol(handle, symbol),")
    push!(lines, "         _symbol(handle, rustcall′RustCall.ffi_panic_symbol(symbol)),")
    push!(lines, "         _required_symbol(handle, free_symbol),")
    push!(lines, "         gen.alive))")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "# The constructor arm: the allocating wrapper, its channel, and the")
    push!(lines, "# destructor and flag the resulting object carries -- one deref (#277).")
    push!(lines, "function _ctor_target(cache::rustcall′RustCall.CrateTargetCache, symbol::rustcall′Base.String, free_symbol::rustcall′Base.String)")
    push!(lines, "    hit = rustcall′RustCall.crate_target_hit(cache, _CTOR_TARGET)")
    push!(lines, "    hit === rustcall′Base.nothing || return hit")
    push!(lines, "    epoch = rustcall′RustCall.artifact_epoch()")
    push!(lines, "    gen = _LIB_GEN[]")
    push!(lines, "    handle = _live_handle(gen)")
    push!(lines, "    return rustcall′RustCall.publish_crate_target!(cache, epoch,")
    push!(lines, "        (_required_symbol(handle, symbol),")
    push!(lines, "         _symbol(handle, rustcall′RustCall.ffi_panic_symbol(symbol)),")
    push!(lines, "         _symbol(handle, free_symbol),")
    push!(lines, "         gen.alive,")
    push!(lines, "         _symbol(handle, rustcall′RustCall.ffi_panic_symbol(free_symbol))))")
    push!(lines, "end")
    push!(lines, "")
    push!(lines, "# A struct's destructor and the liveness flag of the image that exports it,")
    push!(lines, "# from the same deref (#249, #277).")
    push!(lines, "function _struct_generation(cache::rustcall′RustCall.CrateTargetCache, free_symbol::rustcall′Base.String)")
    push!(lines, "    hit = rustcall′RustCall.crate_target_hit(cache, _FREE_TARGET)")
    push!(lines, "    hit === rustcall′Base.nothing || return hit")
    push!(lines, "    epoch = rustcall′RustCall.artifact_epoch()")
    push!(lines, "    gen = _LIB_GEN[]")
    push!(lines, "    # Not published: an unloaded module has no snapshot to keep.")
    push!(lines, "    gen.handle == rustcall′Base.C_NULL && return (rustcall′Base.Ptr{rustcall′Base.Cvoid}(rustcall′Base.C_NULL), gen.alive, rustcall′Base.Ptr{rustcall′Base.Cvoid}(rustcall′Base.C_NULL))")
    push!(lines, "    return rustcall′RustCall.publish_crate_target!(cache, epoch,")
    push!(lines, "        (_symbol(gen.handle, free_symbol),")
    push!(lines, "         gen.alive,")
    push!(lines, "         _symbol(gen.handle, rustcall′RustCall.ffi_panic_symbol(free_symbol))))")
    push!(lines, "end")
    push!(lines, "")
    # The channel is resolved by the caller, before the wrapper call: it is a
    # thread-local in the image, so nothing may yield between the two (#244).
    push!(lines, "_guard_panic(value, channel::rustcall′Base.Ptr{rustcall′Base.Cvoid}, name::rustcall′Base.String) =")
    push!(lines, "    rustcall′RustCall.guard_rust_panic_ptr(value, channel, name)")
    # For a call that returned an owned buffer still to be decoded (#460).
    push!(lines, "_guard_panic(value, channel::rustcall′Base.Ptr{rustcall′Base.Cvoid}, name::rustcall′Base.String, free_ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid}) =")
    push!(lines, "    rustcall′RustCall.guard_rust_panic_ptr(value, channel, name, free_ptr)")
    push!(lines, "")

    # Generate function wrappers of the crate root; items inside modules go
    # into the submodules below (#300).
    tree = _module_tree(info)
    _check_module_names(tree)
    # Every parameter named against the definitions it lands in (#526).
    tree = _rename_crate_tree(tree; strict = strict)
    append!(lines, _function_declarations_source(tree))
    for func in tree.functions
        _function_skipped!(func) && continue
        code = _emit_function_code(func; strict = strict)
        push!(lines, code)
        push!(lines, "")
    end

    # Generate struct wrappers
    colliding = _static_method_collisions(tree.functions, tree.structs)
    for s in tree.structs
        code = _emit_struct_code(s; strict = strict, colliding = colliding)
        push!(lines, code)
        push!(lines, "")
    end

    # One Julia submodule per Rust module (#300).
    append!(lines, _submodule_code(tree; strict = strict))

    # Module end
    push!(lines, "end # module $mod_name")

    return join(lines, "\n")
end

"""
    _emit_string_arg_plan(func_or_method) -> (bindings_str, preserve_str, converted_args_str, frame_str)

Source-text counterpart of `_string_arg_plan` for the file emitter (free
functions and struct methods alike).
"""
function _emit_string_arg_plan(func::Union{RustFunctionSignature, RustMethod})
    bindings, preserved, call_args, frame = _string_arg_plan(func, identity)
    bindings_str = join(("    " * _emitted_source(b) for b in bindings), "\n")
    preserve_str = join(_emitted_source.(preserved), " ")
    # Printed as one argument list, not argument by argument: a lone
    # `Base.@cfunction` prints in its space-separated form, which inside a
    # call swallows every argument after it (a callback argument followed by
    # another one did not load from a written file). Inside a call Julia's
    # printer gives it parentheses.
    converted_args_str = String(chop(_emitted_source(Expr(:call, :f, call_args...)); head = 2, tail = 1))
    frame_str = frame === nothing ? "" : string(frame)
    return bindings_str, preserve_str, converted_args_str, frame_str
end

"""
    _emit_in_callback_frame(frame_str, code) -> String

Source-text twin of `_in_callback_frame` (#296): `code`, or `code` inside a
`try … finally` that pops the `CallbackFrame` named by `frame_str`.
"""
function _emit_in_callback_frame(frame_str::AbstractString, code::AbstractString)
    isempty(frame_str) && return String(code)
    return "(try $(code) finally rustcall′RustCall._pop_callback_frame!($(frame_str)) end)"
end

"""
    _emit_function_code(func::RustFunctionSignature) -> String

Generate Julia code for a function wrapper as a string.
"""
function _emit_function_code(func::RustFunctionSignature; strict::Symbol = _ffi_strict())
    # The item every position below is filed under (#454), named before the
    # argument plan, which records first.
    _boundary_item!(_boundary_label(func))
    # An item the Rust codegen refuses gets no wrapper (#491).
    _rust_refused_item!(func.skip_reason, func.name) && return ""
    func_name = julia_function_name(func)
    # The generated Julia function keeps the Rust name; the symbol it looks up
    # is the additive wrapper `rustcall_<name>` (#279).
    sym = func.symbol
    arg_names = func.arg_names
    # Resolved before the call in every branch below: the panic channel is a
    # thread-local in the image, so nothing may yield between the wrapper call
    # and the read of the channel (#244).
    channel_var = _generated_local("panic_channel", arg_names)
    # Bound in every branch below, not just the plain one: the string branches
    # call through the same snapshot.
    ptr_var = _generated_local("func_ptr", arg_names)
    free_var = _generated_local("free_ptr", arg_names)
    # This call site's snapshot cache (#253), declared beside the wrapper.
    cache_var = _target_cache_ref(:fn, sym)

    # Build argument conversions (string arguments become (ptr, len) pairs)
    arg_syms = join(arg_names, ", ")
    bindings_str, preserve_str, converted_args_str, frame_str = _emit_string_arg_plan(func)
    prologue = isempty(bindings_str) ? "" : bindings_str * "\n"

    # Result/Option return types are reported by the manifest
    if func.return_kind == :result
        return _emit_result_function_code(func, arg_syms, converted_args_str; prologue, preserve_str, strict, frame_str)
    elseif func.return_kind == :py_result
        return _emit_py_result_function_code(func, arg_syms, converted_args_str; prologue,
                                             preserve_str, strict, frame_str)
    elseif func.return_kind == :option
        return _emit_option_function_code(func, arg_syms, converted_args_str; prologue, preserve_str, strict, frame_str)
    elseif ffi_owned_string_return(_ffi_function_return(func))
        return """
$(_target_cache_source(:fn, sym))
function $func_name($arg_syms)
$(prologue)    $ptr_var, $channel_var, $free_var = _call_target($cache_var, "$sym", "$(_ffi_function_return(func).free_symbol)")
    _guard_panic($(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall._call_rust_owned_string_ptr($ptr_var, $free_var, $converted_args_str)"))), $channel_var, "$func_name")
end
export $func_name"""
    elseif ffi_borrowed_string_return(_ffi_function_return(func))
        return """
$(_target_cache_source(:fn, sym))
function $func_name($arg_syms)
$(prologue)    $ptr_var, $channel_var = _call_target($cache_var, "$sym")
    _guard_panic($(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall._call_rust_borrowed_string_ptr($ptr_var, $converted_args_str)"))), $channel_var, "$func_name")
end
export $func_name"""
    else
        # Standard function
        ret_type_str = _emitted_type_source(ffi_return_symbol_or_throw(func.return_type, func.return_abi,
                                                                       _ffi_context(func); strict = strict))
        return """
$(_target_cache_source(:fn, sym))
function $func_name($arg_syms)
$(prologue)    $ptr_var, $channel_var = _call_target($cache_var, "$sym")
    _guard_panic($(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $ret_type_str, $converted_args_str)"))), $channel_var, "$func_name")
end
export $func_name"""
    end
end

function _emit_result_function_code(func::RustFunctionSignature, arg_syms::String, converted_args_str::String;
                                    prologue::String = "", preserve_str::String = "",
                                    strict::Symbol = _ffi_strict(), frame_str::String = "")
    func_name = julia_function_name(func)
    ctx = _ffi_context(func)
    # The payload fields carry the C slot; see `_generate_result_function_wrapper`.
    ok_surface, ok_slot = ffi_payload_symbols(func.ok_type, func.ok_abi, ctx;
                                              position = "Ok payload", strict = strict)
    err_surface, err_slot = ffi_payload_symbols(func.err_type, func.err_abi, ctx;
                                                position = "Err payload", strict = strict)
    ok_type_str = _emitted_type_source(ok_surface)
    err_type_str = _emitted_type_source(err_surface)
    ok_slot_str = _emitted_type_source(ok_slot)
    err_slot_str = _emitted_type_source(err_slot)
    sym = func.symbol
    c_result_struct_name = "CResult_$(func.ffi_name)"
    ptr_var = _generated_local("func_ptr", func.arg_names)
    c_var = _generated_local("c_result", func.arg_names)
    channel_var = _generated_local("panic_channel", func.arg_names)
    free_var = _generated_local("free_ptr", func.arg_names)
    free_str = _payload_free_symbol(func.ffi_name, (func.ok_abi, func.err_abi))
    cache_var = _target_cache_ref(:fn, sym)
    target = isempty(free_str) ?
        "$ptr_var, $channel_var = _call_target($cache_var, \"$sym\")" :
        "$ptr_var, $channel_var, $free_var = _call_target($cache_var, \"$sym\", \"$free_str\")"
    free_expr = isempty(free_str) ? "rustcall′Base.C_NULL" : string(free_var)

    return """
$(_target_cache_source(:fn, sym))
struct $c_result_struct_name <: rustcall′RustCall.FFIByValue
    is_ok::rustcall′Base.UInt8
    ok_value::$ok_slot_str
    err_value::$err_slot_str
end

function $func_name($arg_syms)
$(prologue)    $target
    $c_var = $(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $c_result_struct_name, $converted_args_str)")))
    _guard_panic($c_var, $channel_var, "$func_name", $free_expr)
    if $c_var.is_ok == 1
        rustcall′RustCall.RustResult{$ok_type_str, $err_type_str}(true, rustcall′RustCall._result_payload($ok_type_str, $c_var.ok_value, $free_expr))
    else
        rustcall′RustCall.RustResult{$ok_type_str, $err_type_str}(false, rustcall′RustCall._result_payload($err_type_str, $c_var.err_value, $free_expr))
    end
end
export $func_name"""
end

"""
    _emit_py_result_function_code(func, arg_syms, converted_args_str; ...) -> String

Source-text counterpart of `_generate_py_result_function_wrapper` (#275
Phase 2).
"""
function _emit_py_result_function_code(func::RustFunctionSignature, arg_syms::String,
                                       converted_args_str::String;
                                       prologue::String = "", preserve_str::String = "",
                                       strict::Symbol = _ffi_strict(), frame_str::String = "")
    func_name = julia_function_name(func)
    ok_type_str, ok_slot_str, is_unit =
        _py_result_types(func.ok_type, func.ok_abi, _ffi_context(func); strict = strict)
    ok_type_str, ok_slot_str = _emitted_type_source(ok_type_str), _emitted_type_source(ok_slot_str)
    sym = func.symbol
    c_result_struct_name = "CResult_$(func.ffi_name)"
    ptr_var = _generated_local("func_ptr", func.arg_names)
    c_var = _generated_local("c_result", func.arg_names)
    channel_var = _generated_local("panic_channel", func.arg_names)
    free_var = _generated_local("free_ptr", func.arg_names)
    free_str = _payload_free_symbol(func.ffi_name, (func.ok_abi,))
    cache_var = _target_cache_ref(:fn, sym)
    target = isempty(free_str) ?
        "$ptr_var, $channel_var = _call_target($cache_var, \"$sym\")" :
        "$ptr_var, $channel_var, $free_var = _call_target($cache_var, \"$sym\", \"$free_str\")"
    free_expr = isempty(free_str) ? "rustcall′Base.C_NULL" : string(free_var)
    ok_value = is_unit ? "rustcall′Base.nothing" :
        "rustcall′RustCall._result_payload($ok_type_str, $c_var.ok_value, $free_expr)"

    return """
$(_target_cache_source(:fn, sym))
# RustCall's own mirror of a `#[repr(C)]` aggregate it generated (#245).
struct $c_result_struct_name <: rustcall′RustCall.FFIByValue
    is_ok::rustcall′Base.UInt8
    ok_value::$ok_slot_str
    err_value::rustcall′Base.Int32
end

function $func_name($arg_syms)
$(prologue)    $target
    $c_var = $(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $c_result_struct_name, $converted_args_str)")))
    _guard_panic($c_var, $channel_var, "$func_name", $free_expr)
    if $c_var.is_ok == 1
        rustcall′RustCall.RustResult{$ok_type_str, rustcall′Base.String}(true, $ok_value)
    else
        rustcall′RustCall.RustResult{$ok_type_str, rustcall′Base.String}(false, rustcall′RustCall.PYO3_OPAQUE_ERROR)
    end
end
export $func_name"""
end

function _emit_option_function_code(func::RustFunctionSignature, arg_syms::String, converted_args_str::String;
                                    prologue::String = "", preserve_str::String = "",
                                    strict::Symbol = _ffi_strict(), frame_str::String = "")
    func_name = julia_function_name(func)
    inner_surface, inner_slot =
        ffi_payload_symbols(func.inner_type, func.inner_abi, _ffi_context(func);
                            position = "Some payload", strict = strict)
    inner_type_str = _emitted_type_source(inner_surface)
    inner_slot_str = _emitted_type_source(inner_slot)
    sym = func.symbol
    c_option_struct_name = "COption_$(func.ffi_name)"
    ptr_var = _generated_local("func_ptr", func.arg_names)
    c_var = _generated_local("c_option", func.arg_names)
    channel_var = _generated_local("panic_channel", func.arg_names)
    free_var = _generated_local("free_ptr", func.arg_names)
    free_str = _payload_free_symbol(func.ffi_name, (func.inner_abi,))
    cache_var = _target_cache_ref(:fn, sym)
    target = isempty(free_str) ?
        "$ptr_var, $channel_var = _call_target($cache_var, \"$sym\")" :
        "$ptr_var, $channel_var, $free_var = _call_target($cache_var, \"$sym\", \"$free_str\")"
    free_expr = isempty(free_str) ? "rustcall′Base.C_NULL" : string(free_var)

    return """
$(_target_cache_source(:fn, sym))
struct $c_option_struct_name <: rustcall′RustCall.FFIByValue
    is_some::rustcall′Base.UInt8
    value::$inner_slot_str
end

function $func_name($arg_syms)
$(prologue)    $target
    $c_var = $(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $c_option_struct_name, $converted_args_str)")))
    _guard_panic($c_var, $channel_var, "$func_name", $free_expr)
    if $c_var.is_some == 1
        rustcall′RustCall.RustOption{$inner_type_str}(true, rustcall′RustCall._result_payload($inner_type_str, $c_var.value, $free_expr))
    else
        rustcall′RustCall.RustOption{$inner_type_str}(false, rustcall′Base.nothing)
    end
end
export $func_name"""
end

"""
    _emit_struct_code(info::RustStructInfo) -> String

Generate Julia code for a struct wrapper as a string.
"""
function _emit_struct_code(info::RustStructInfo; strict::Symbol = _ffi_strict(),
                           colliding::Set{String} = Set{String}())
    # A struct the Rust codegen refuses (a generic crate struct, #462) gets no
    # Julia type; the report names it at its entry point (#503).
    if !_binds_julia_struct(info)
        _boundary_item!(_boundary_label(info))
        _rust_refused_item!(info.skip_reason, info.name)
        return ""
    end
    struct_name = julia_struct_name(info)
    release_alive = _python_owned_handle(info) ? "rustcall′Base.Ref(true)" : "rustcall′alive"
    free_symbol = ffi_struct_free_symbol(info.ffi_name)
    free_cache = _target_cache_ref(:free, free_symbol)

    lines = String[]

    # Struct definition
    push!(lines, _target_cache_source(:free, free_symbol))
    push!(lines, "mutable struct $struct_name")
    push!(lines, "    ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid}")
    # Captured at construction: the destructor, and the flag that says whether
    # the library is still loaded. A finalizer must take no lock, resolve no
    # symbol and log nothing (#249).
    push!(lines, "    free_ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid}")
    push!(lines, "    alive::rustcall′Base.RefValue{rustcall′Base.Bool}")
    push!(lines, "    free_channel::rustcall′Base.Ptr{rustcall′Base.Cvoid}")
    push!(lines, "")
    push!(lines, "    function $struct_name(rustcall′ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′free_ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid}, rustcall′alive::rustcall′Base.RefValue{rustcall′Base.Bool}, rustcall′free_channel::rustcall′Base.Ptr{rustcall′Base.Cvoid} = rustcall′Base.C_NULL)")
    push!(lines, "        rustcall′obj = new(rustcall′ptr, rustcall′free_ptr, rustcall′alive, rustcall′free_channel)")
    push!(lines, "        rustcall′Base.finalizer(rustcall′RustCall.finalize_rust_object!, rustcall′obj)")
    push!(lines, "        return rustcall′obj")
    push!(lines, "    end")
    push!(lines, "")
    push!(lines, "    function $struct_name(rustcall′ptr::rustcall′Base.Ptr{rustcall′Base.Cvoid})")
    push!(lines, "        rustcall′free_ptr, rustcall′alive, rustcall′free_channel = _struct_generation($free_cache, $(repr(free_symbol)))")
    push!(lines, "        return $struct_name(rustcall′ptr, rustcall′free_ptr, $release_alive, rustcall′free_channel)")
    push!(lines, "    end")
    push!(lines, "end")
    push!(lines, "export $struct_name")
    push!(lines, "function rustcall′Base.show(rustcall′io::rustcall′Base.IO, rustcall′self::$struct_name)")
    push!(lines, "    rustcall′Base.print(rustcall′io, rustcall′Base.nameof(@__MODULE__), \".$struct_name(\")")
    push!(lines, "    rustcall′Base.show(rustcall′io, rustcall′Base.getfield(rustcall′self, :ptr))")
    push!(lines, "    rustcall′Base.print(rustcall′io, \")\")")
    push!(lines, "end")
    push!(lines, "function rustcall′Base.show(rustcall′io::rustcall′Base.IO, ::MIME\"text/plain\", rustcall′self::$struct_name)")
    push!(lines, "    rustcall′Base.show(rustcall′io, rustcall′self)")
    push!(lines, "end")
    push!(lines, "")

    # Method wrappers
    for m in info.methods
        code = _emit_method_code(info, m; strict = strict, bare = !(julia_method_name(m) in colliding))
        push!(lines, code)
        push!(lines, "")
    end

    # Property access. The same split as `_generate_property_accessors`: a
    # getter branch per readable field, a setter branch per writable one, and
    # a write-only `#[pyo3(set)]` field is a property with no read (#307 review).
    readable_fields = [(name, type) for (name, type) in info.fields if field_is_accessible(info, name)]
    writable_fields = [(name, type) for (name, type) in info.fields if field_is_writable(info, name)]
    property_fields = [(name, type) for (name, type) in info.fields
                       if field_is_accessible(info, name) || field_is_writable(info, name)]

    if !isempty(property_fields)
        # Each property branch is its own call site and gets its own snapshot
        # cache (#253). The `:prop` kind keeps it distinct from the accessor
        # helper's, which the expression emitter builds for the same symbol.
        for (field_name, _) in readable_fields
            push!(lines, _target_cache_source(:prop, info.field_getters[field_name]))
        end
        for (field_name, _) in writable_fields
            push!(lines, _target_cache_source(:prop, info.field_setters[field_name]))
        end
        push!(lines, "")
        # getproperty
        push!(lines, "function rustcall′Base.getproperty(rustcall′self::$struct_name, rustcall′field::rustcall′Base.Symbol)")
        push!(lines, "    if rustcall′field === :ptr")
        push!(lines, "        return rustcall′Base.getfield(rustcall′self, :ptr)")
        push!(lines, "    end")
        push!(lines, "    rustcall′RustCall._check_not_freed(rustcall′self, \"$struct_name\")")
        for (field_name, field_type) in readable_fields
            getter_fn = info.field_getters[field_name]
            read = _crate_field_read_source(info, field_name, field_type, getter_fn,
                                            "rustcall′Base.getfield(rustcall′self, :ptr)",
                                            _target_cache_ref(:prop, getter_fn); strict = strict)
            push!(lines, "    if rustcall′field === $(repr(Symbol(julia_field_name(field_name))))")
            push!(lines, "        return $read")
            push!(lines, "    end")
        end
        push!(lines, "    rustcall′Base.error(\"type $struct_name has no field \$rustcall′field\")")
        push!(lines, "end")
        push!(lines, "")

        # setproperty!
        push!(lines, "function rustcall′Base.setproperty!(rustcall′self::$struct_name, rustcall′field::rustcall′Base.Symbol, rustcall′value)")
        push!(lines, "    if rustcall′field === :ptr")
        push!(lines, "        rustcall′Base.error(\"cannot set internal field :ptr\")")
        push!(lines, "    end")
        push!(lines, "    rustcall′RustCall._check_not_freed(rustcall′self, \"$struct_name\")")
        for (field_name, field_type) in writable_fields
            setter_fn = info.field_setters[field_name]
            write = _crate_field_write_source(info, field_name, field_type, setter_fn,
                                              "rustcall′Base.getfield(rustcall′self, :ptr)", "rustcall′value",
                                              _target_cache_ref(:prop, setter_fn); strict = strict)
            push!(lines, "    if rustcall′field === $(repr(Symbol(julia_field_name(field_name))))")
            push!(lines, "        $write")
            push!(lines, "        return rustcall′value")
            push!(lines, "    end")
        end
        push!(lines, "    rustcall′Base.error(\"type $struct_name has no field \$rustcall′field\")")
        push!(lines, "end")
        push!(lines, "")

        # propertynames
        field_syms = join([repr(Symbol(julia_field_name(name))) for (name, _) in property_fields], ", ")
        push!(lines, "function rustcall′Base.propertynames(rustcall′self::$struct_name)")
        push!(lines, "    ($field_syms,)")
        push!(lines, "end")
    end

    return join(lines, "\n")
end

"""
    _quote_preserved(preserved, call) -> Expr

`GC.@preserve <objects> <call>`, or just `call` when `preserved` is empty.
The expression twin of `_emit_preserved`: `GC.@preserve` needs at least one
object, so an empty list must not produce the macro call at all.
"""
_quote_preserved(preserved, call) =
    isempty(preserved) ? call : Expr(:macrocall, Expr(:., GlobalRef(Base, :GC), QuoteNode(Symbol("@preserve"))),
                                     nothing, preserved..., call)

"""
    _emit_preserved(preserve_str, call) -> String

`GC.@preserve <objects>, <call>` as source text (through the file's
`rustcall′Base` alias, #528), or just `<call>` when there is nothing to
preserve.

`GC.@preserve` takes at least one object followed by the expression, so the
empty case has to omit the macro entirely rather than emit
`GC.@preserve(, call)`. The parenthesized form is used because the result is
nested inside `_guard_panic(...)`, and it needs the objects **comma**-separated
where the statement form separates them by spaces.
"""
function _emit_preserved(preserve_str::AbstractString, call::AbstractString)
    objects = filter(!isempty, split(strip(preserve_str)))
    isempty(objects) && return call
    return "rustcall′Base.GC.@preserve($(join(objects, ", ")), $call)"
end

"""
    _emit_method_code(struct_info::RustStructInfo, method::RustMethod) -> String

Generate Julia code for a method wrapper as a string.
"""
function _emit_method_code(struct_info::RustStructInfo, method::RustMethod;
                           strict::Symbol = _ffi_strict(), bare::Bool = true)
    # The item every position below is filed under (#454), named before the
    # argument plan, which records first.
    _boundary_item!(_boundary_label(struct_info, method))
    # A method the Rust codegen refuses gets no wrapper (#491).
    _rust_refused_item!(method.skip_reason, method.name) && return ""
    struct_name = julia_struct_name(struct_info)
    method_name = julia_method_name(method)
    # Exported symbol (`rustcall_<Struct>_<method>`, #279) and the owner of the
    # per-method string buffers, both off the struct's FFI name (#300). The
    # manifest states the owner (#342); the derivation stands in only for an
    # entry that states none.
    wrapper_name = method_wrapper_symbol(struct_info.ffi_name, method)
    helper_owner = _method_string_owner(method, "$(struct_info.ffi_name)_$(rust_name(method.name))")

    arg_syms = join(method.arg_names, ", ")

    # Same shape as `_generate_crate_method_wrapper`: string arguments are
    # (ptr, len) pairs under GC.@preserve, string results come back through
    # the per-method `<Struct>_<method>_RustCallOwnedString` buffer.
    bindings_str, preserve_str, converted_args_str, frame_str = _emit_string_arg_plan(method)
    prologue = isempty(bindings_str) ? "" : bindings_str * "\n"
    # `self` is preserved too: a borrowed `&str` result points into the Rust
    # object, which the finalizer of a temporary could free mid-call.
    method.is_static || (preserve_str = strip("rustcall′self " * preserve_str))
    ptr_var = _generated_local("func_ptr", method.arg_names)
    c = _ffi_method_return(method, helper_owner)

    all_args = String[]
    method.is_static || push!(all_args, "rustcall′Base.getfield(rustcall′self, :ptr)")
    isempty(converted_args_str) || push!(all_args, converted_args_str)
    args_str = join(all_args, ", ")

    free_var = _generated_local("free_ptr", method.arg_names)
    channel_var = _generated_local("panic_channel", method.arg_names)
    free_channel_var = _generated_local("free_panic_channel", method.arg_names)
    cache_var = _target_cache_ref(:m, wrapper_name)
    target = "$ptr_var, $channel_var = _call_target($cache_var, \"$wrapper_name\")"
    alive_var = _generated_local("alive", method.arg_names)
    release_alive = _python_owned_handle(struct_info) ? "rustcall′Base.Ref(true)" : string(alive_var)
    if method.return_kind === :py_result
        return _emit_py_result_method_code(struct_info, method, arg_syms, converted_args_str,
                                           wrapper_name; prologue, preserve_str, strict, bare, frame_str)
    end
    method_label = "$(struct_name)::$(method_name)"
    # `Result` / `Option` returns are lowered like a free function's (#268):
    # the aggregate mirror is emitted above the wrapper and the channel is read
    # before either payload is decoded.
    if method.return_kind === :result || method.return_kind === :option
        plan = _method_payload_plan(struct_info, method, helper_owner; strict = strict)
        c_var = _generated_local("c_payload", method.arg_names)
        payload_target = isempty(plan.free_symbol) ?
            "$ptr_var, $channel_var = _call_target($cache_var, \"$wrapper_name\")" :
            "$ptr_var, $channel_var, $free_var = _call_target($cache_var, \"$wrapper_name\", \"$(plan.free_symbol)\")"
        free_expr = isempty(plan.free_symbol) ? "rustcall′Base.C_NULL" : string(free_var)
        payload_body = """
$(prologue)    $payload_target
    $c_var = $(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $(plan.struct_name), $args_str)")))
    _guard_panic($c_var, $channel_var, "$method_label", $free_expr)
$(_emit_payload_decode(plan, c_var, free_expr))"""
        return _emit_method_definition(struct_name, method, arg_syms, payload_body;
                                       predef = _target_cache_source(:m, wrapper_name) *
                                                "\n\n" * plan.source, bare = bare)
    end
    call = if method.returns_boxed_struct
        target = "$ptr_var, $channel_var, $free_var, $alive_var, $free_channel_var = " *
                 "_ctor_target($cache_var, \"$wrapper_name\", \"$(ffi_struct_free_symbol(struct_info.ffi_name))\")"
        "$struct_name(rustcall′RustCall.call_rust_function($ptr_var, rustcall′Base.Ptr{rustcall′Base.Cvoid}, $args_str), $free_var, $release_alive, $free_channel_var)"
    elseif ffi_owned_string_return(c)
        target = "$ptr_var, $channel_var, $free_var = _call_target($cache_var, \"$wrapper_name\", \"$(c.free_symbol)\")"
        "rustcall′RustCall._call_rust_owned_string_ptr($ptr_var, $free_var, $args_str)"
    elseif ffi_borrowed_string_return(c)
        "rustcall′RustCall._call_rust_borrowed_string_ptr($ptr_var, $args_str)"
    else
        ret_type_str = _emitted_type_source(ffi_return_symbol_or_throw(method.return_type, method.return_abi,
                                                         _ffi_context(method, struct_name);
                                                         strict = strict))
        "rustcall′RustCall.call_rust_function($ptr_var, $ret_type_str, $args_str)"
    end
    body = """
$(prologue)    $target
    _guard_panic($(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, call))), $channel_var, "$method_label")"""

    # The call site's snapshot cache, declared at module scope beside the
    # wrapper that uses it (#253).
    return _emit_method_definition(struct_name, method, arg_syms, body;
                                   predef = _target_cache_source(:m, wrapper_name), bare = bare)
end

# The `function ... end` (and `export`) wrapper shared by every method-emitting
# branch, so a new return shape cannot forget the freed-object check or the
# receiver argument. `predef` is emitted above the definition. `bare` says
# whether a static method also gets its bare `name(args)` form (#323).
function _emit_method_definition(struct_name::AbstractString, method::RustMethod,
                                 arg_syms::AbstractString, body::AbstractString;
                                 predef::AbstractString = "", bare::Bool = true)
    method_name = julia_method_name(method)
    definition = if method.is_static && method.is_constructor
        """
function $struct_name($arg_syms)
$body
end"""
    elseif method.is_static
        # Type-dispatched — `shout(Labeler, s)` for `Labeler::shout` — so it
        # never shares a method table with a free function of the same name;
        # the bare form only while nothing else defines it (#323).
        comma_args = isempty(arg_syms) ? "" : ", $arg_syms"
        # Own argument names in the delegator, so an argument called like the
        # method or the struct cannot shadow them in the forwarding body.
        dargs = join(("rustcall′arg$i" for i in eachindex(method.arg_names)), ", ")
        dcomma = isempty(dargs) ? "" : ", $dargs"
        bare_def = bare ? "\n$method_name($dargs) = $method_name($struct_name$dcomma)" : ""
        """
function $method_name(::rustcall′Base.Type{$struct_name}$comma_args)
$body
end$bare_def
export $method_name"""
    else
        self_args = isempty(arg_syms) ? "" : ", $arg_syms"
        """
function $method_name(rustcall′self::$struct_name$self_args)
    rustcall′RustCall._check_not_freed(rustcall′self, "$struct_name")
$body
end
export $method_name"""
    end
    return isempty(predef) ? definition : predef * "\n\n" * definition
end

# The source-text counterpart of `_payload_decode_expr`.
function _emit_payload_decode(plan::MethodPayloadPlan, c_var, free_expr::AbstractString)
    if plan.kind === :result
        ok_t, err_t = map(_emitted_source, plan.surface)
        return """
    if $c_var.is_ok == 1
        rustcall′RustCall.RustResult{$ok_t, $err_t}(true, rustcall′RustCall._result_payload($ok_t, $c_var.ok_value, $free_expr))
    else
        rustcall′RustCall.RustResult{$ok_t, $err_t}(false, rustcall′RustCall._result_payload($err_t, $c_var.err_value, $free_expr))
    end"""
    end
    inner_t = _emitted_source(first(plan.surface))
    return """
    if $c_var.is_some == 1
        rustcall′RustCall.RustOption{$inner_t}(true, rustcall′RustCall._result_payload($inner_t, $c_var.value, $free_expr))
    else
        rustcall′RustCall.RustOption{$inner_t}(false, rustcall′Base.nothing)
    end"""
end

"""
    _emit_py_result_method_code(info, method, ...) -> String

Source-text counterpart of `_generate_py_result_method_wrapper` (#275 Phase 2).
"""
function _emit_py_result_method_code(info::RustStructInfo, method::RustMethod,
                                     arg_syms::String, converted_args_str::String,
                                     wrapper_name::String;
                                     prologue::AbstractString = "",
                                     preserve_str::AbstractString = "",
                                     strict::Symbol = _ffi_strict(), bare::Bool = true,
                                     frame_str::AbstractString = "")
    struct_name = julia_struct_name(info)
    method_name = julia_method_name(method)
    boxed = method.returns_boxed_struct
    ok_type_str, ok_slot_str, is_unit = boxed ?
        (struct_name, "rustcall′Base.Ptr{rustcall′Base.Cvoid}", false) :
        _py_result_types(method.ok_type, method.ok_abi,
                         _ffi_context(method, struct_name); strict = strict)
    ok_type_str, ok_slot_str = _emitted_type_source(ok_type_str), _emitted_type_source(ok_slot_str)
    helper_owner = _method_string_owner(method, "$(info.ffi_name)_$(rust_name(method.name))")
    c_result_struct_name = "CResult_$helper_owner"
    ptr_var = _generated_local("func_ptr", method.arg_names)
    c_var = _generated_local("c_result", method.arg_names)
    channel_var = _generated_local("panic_channel", method.arg_names)
    free_var = _generated_local("free_ptr", method.arg_names)
    alive_var = _generated_local("alive", method.arg_names)
    release_alive = _python_owned_handle(info) ? "rustcall′Base.Ref(true)" : string(alive_var)
    free_channel_var = _generated_local("free_panic_channel", method.arg_names)

    all_args = String[]
    method.is_static || push!(all_args, "rustcall′Base.getfield(rustcall′self, :ptr)")
    isempty(converted_args_str) || push!(all_args, converted_args_str)
    args_str = join(all_args, ", ")
    method_label = "$(struct_name)::$(method_name)"
    payload_free = _payload_free_symbol(helper_owner, (method.ok_abi,))
    cache_var = _target_cache_ref(:m, wrapper_name)
    target = if boxed
        "$ptr_var, $channel_var, $free_var, $alive_var, $free_channel_var = " *
        "_ctor_target($cache_var, \"$wrapper_name\", \"$(ffi_struct_free_symbol(info.ffi_name))\")"
    elseif !isempty(payload_free)
        "$ptr_var, $channel_var, $free_var = " *
        "_call_target($cache_var, \"$wrapper_name\", \"$payload_free\")"
    else
        "$ptr_var, $channel_var = _call_target($cache_var, \"$wrapper_name\")"
    end
    free_expr = isempty(payload_free) ? "rustcall′Base.C_NULL" : string(free_var)
    ok_value = if is_unit
        "rustcall′Base.nothing"
    elseif boxed
        "$struct_name($c_var.ok_value, $free_var, $release_alive, $free_channel_var)"
    else
        "rustcall′RustCall._result_payload($ok_type_str, $c_var.ok_value, $free_expr)"
    end

    body = """
$(prologue)    $target
    $c_var = $(_emit_in_callback_frame(frame_str, _emit_preserved(preserve_str, "rustcall′RustCall.call_rust_function($ptr_var, $c_result_struct_name, $args_str)")))
    _guard_panic($c_var, $channel_var, "$method_label", $free_expr)
    if $c_var.is_ok == 1
        rustcall′RustCall.RustResult{$ok_type_str, rustcall′Base.String}(true, $ok_value)
    else
        rustcall′RustCall.RustResult{$ok_type_str, rustcall′Base.String}(false, rustcall′RustCall.PYO3_OPAQUE_ERROR)
    end"""

    declaration = """
# The call site's snapshot cache, beside the wrapper that uses it (#253).
$(_target_cache_source(:m, wrapper_name))
# RustCall's own mirror of a `#[repr(C)]` aggregate it generated (#245).
struct $c_result_struct_name <: rustcall′RustCall.FFIByValue
    is_ok::rustcall′Base.UInt8
    ok_value::$ok_slot_str
    err_value::rustcall′Base.Int32
end
"""

    if method.is_static && method.is_constructor
        return """$declaration
function $struct_name($arg_syms)
$body
end"""
    elseif method.is_static
        # Type-dispatched, bare form only without a name collision (#323); see
        # `_emit_method_definition`.
        comma_args = isempty(arg_syms) ? "" : ", $arg_syms"
        # Own argument names in the delegator, so an argument called like the
        # method or the struct cannot shadow them in the forwarding body.
        dargs = join(("rustcall′arg$i" for i in eachindex(method.arg_names)), ", ")
        dcomma = isempty(dargs) ? "" : ", $dargs"
        bare_def = bare ? "\n$method_name($dargs) = $method_name($struct_name$dcomma)" : ""
        return """$declaration
function $method_name(::rustcall′Base.Type{$struct_name}$comma_args)
$body
end$bare_def
export $method_name"""
    end
    self_args = isempty(arg_syms) ? "" : ", $arg_syms"
    return """$declaration
function $method_name(rustcall′self::$struct_name$self_args)
    rustcall′RustCall._check_not_freed(rustcall′self, "$struct_name")
$body
end
export $method_name"""
end

# `@rust_crate_static`, an error stub since the `write_bindings_to_file`
# migration, was removed in v0.5 (#417): include the generated file instead.
