# Reading rustc's structured diagnostics.
#
# `rustc --error-format=json` writes one JSON object per line on stderr. That
# is the *only* thing this file parses: it exists so that a decision taken from
# a compiler diagnostic is taken from the diagnostic's fields — its error code,
# its span, its label — rather than from the human-rendered text, which rustc
# is free to reformat.
#
# It is deliberately a minimal reader rather than a JSON dependency: the input
# is machine-generated by one known producer, and RustCall's dependency list is
# a design constraint of its own. The grammar implemented is all of RFC 8259
# except that duplicate object keys keep the last value; numbers become
# Float64 unless they are integral.

"""
    JSONParseError

Raised when a line of rustc's `--error-format=json` output is not valid JSON.
Callers treat it as "this line carried no diagnostic", never as a build
failure: rustc may prefix its stderr with output of its own.
"""
struct JSONParseError <: Exception
    msg::String
    position::Int
end

Base.showerror(io::IO, e::JSONParseError) =
    print(io, "JSONParseError: ", e.msg, " at byte ", e.position)

"""
    parse_json(text::AbstractString) -> Any

Parse one JSON document into `Dict{String, Any}` / `Vector{Any}` / `String` /
`Float64` / `Int` / `Bool` / `nothing`.

Only used for rustc's `--error-format=json` output (see `rustc_diagnostics`).
"""
function parse_json(text::AbstractString)
    s = String(text)
    i = _json_skip_ws(s, firstindex(s))
    value, i = _json_value(s, i)
    i = _json_skip_ws(s, i)
    i > ncodeunits(s) || throw(JSONParseError("trailing characters", i))
    return value
end

_json_skip_ws(s::String, i::Int) = begin
    n = ncodeunits(s)
    while i <= n && (s[i] == ' ' || s[i] == '\t' || s[i] == '\n' || s[i] == '\r')
        i = nextind(s, i)
    end
    i
end

function _json_expect(s::String, i::Int, c::Char)
    (i <= ncodeunits(s) && s[i] == c) || throw(JSONParseError("expected '$(c)'", i))
    return nextind(s, i)
end

function _json_value(s::String, i::Int)
    i = _json_skip_ws(s, i)
    i <= ncodeunits(s) || throw(JSONParseError("unexpected end of input", i))
    c = s[i]
    c == '{' && return _json_object(s, i)
    c == '[' && return _json_array(s, i)
    c == '"' && return _json_string(s, i)
    if c == 't'
        startswith(SubString(s, i), "true") || throw(JSONParseError("invalid literal", i))
        return (true, i + 4)
    elseif c == 'f'
        startswith(SubString(s, i), "false") || throw(JSONParseError("invalid literal", i))
        return (false, i + 5)
    elseif c == 'n'
        startswith(SubString(s, i), "null") || throw(JSONParseError("invalid literal", i))
        return (nothing, i + 4)
    end
    return _json_number(s, i)
end

function _json_object(s::String, i::Int)
    i = _json_expect(s, i, '{')
    out = Dict{String, Any}()
    i = _json_skip_ws(s, i)
    if i <= ncodeunits(s) && s[i] == '}'
        return (out, nextind(s, i))
    end
    while true
        i = _json_skip_ws(s, i)
        key, i = _json_string(s, i)
        i = _json_skip_ws(s, i)
        i = _json_expect(s, i, ':')
        value, i = _json_value(s, i)
        out[key] = value
        i = _json_skip_ws(s, i)
        i <= ncodeunits(s) || throw(JSONParseError("unterminated object", i))
        if s[i] == ','
            i = nextind(s, i)
        elseif s[i] == '}'
            return (out, nextind(s, i))
        else
            throw(JSONParseError("expected ',' or '}'", i))
        end
    end
end

function _json_array(s::String, i::Int)
    i = _json_expect(s, i, '[')
    out = Any[]
    i = _json_skip_ws(s, i)
    if i <= ncodeunits(s) && s[i] == ']'
        return (out, nextind(s, i))
    end
    while true
        value, i = _json_value(s, i)
        push!(out, value)
        i = _json_skip_ws(s, i)
        i <= ncodeunits(s) || throw(JSONParseError("unterminated array", i))
        if s[i] == ','
            i = nextind(s, i)
        elseif s[i] == ']'
            return (out, nextind(s, i))
        else
            throw(JSONParseError("expected ',' or ']'", i))
        end
    end
end

function _json_string(s::String, i::Int)
    i = _json_expect(s, i, '"')
    io = IOBuffer()
    n = ncodeunits(s)
    while true
        i <= n || throw(JSONParseError("unterminated string", i))
        c = s[i]
        if c == '"'
            return (String(take!(io)), nextind(s, i))
        elseif c == '\\'
            i = nextind(s, i)
            i <= n || throw(JSONParseError("unterminated escape", i))
            e = s[i]
            if e == 'u'
                cp, i = _json_unicode_escape(s, nextind(s, i))
                print(io, cp)
                continue
            end
            print(io, e == 'n' ? '\n' : e == 't' ? '\t' : e == 'r' ? '\r' :
                      e == 'b' ? '\b' : e == 'f' ? '\f' : e)
            i = nextind(s, i)
        else
            print(io, c)
            i = nextind(s, i)
        end
    end
end

# `\uXXXX`, including a surrogate pair.
function _json_unicode_escape(s::String, i::Int)
    unit(j) = begin
        j + 3 <= ncodeunits(s) || throw(JSONParseError("truncated \\u escape", j))
        parse(UInt16, SubString(s, j, j + 3); base = 16)
    end
    hi = unit(i)
    i += 4
    if 0xD800 <= hi <= 0xDBFF && i + 1 <= ncodeunits(s) && s[i] == '\\' && s[i + 1] == 'u'
        lo = unit(i + 2)
        if 0xDC00 <= lo <= 0xDFFF
            cp = 0x10000 + (UInt32(hi - 0xD800) << 10) + UInt32(lo - 0xDC00)
            return (Char(cp), i + 6)
        end
    end
    return (Char(hi), i)
end

function _json_number(s::String, i::Int)
    n = ncodeunits(s)
    start = i
    isnum(c) = c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E' || ('0' <= c <= '9')
    while i <= n && isnum(s[i])
        i = nextind(s, i)
    end
    i > start || throw(JSONParseError("expected a value", start))
    text = SubString(s, start, prevind(s, i))
    value = tryparse(Int, text)
    value === nothing && (value = tryparse(Float64, text))
    value === nothing && throw(JSONParseError("invalid number '$(text)'", start))
    return (value, i)
end

"""
    rustc_diagnostics(stderr_text::AbstractString) -> Vector{Dict{String, Any}}

The diagnostic objects in `rustc --error-format=json` output, in the order
rustc emitted them.

Lines that are not JSON objects are skipped rather than raising: rustc's stderr
may carry output that is not a diagnostic at all, and a probe that cannot be
read is reported by its caller as "no answer", never as a parse failure.
"""
function rustc_diagnostics(stderr_text::AbstractString)
    out = Dict{String, Any}[]
    for line in eachsplit(String(stderr_text), '\n')
        stripped = strip(line)
        (isempty(stripped) || first(stripped) != '{') && continue
        parsed = try
            parse_json(stripped)
        catch e
            e isa JSONParseError || rethrow(e)
            continue
        end
        parsed isa Dict{String, Any} && push!(out, parsed)
    end
    return out
end

"""
    diagnostic_level(d) -> String
    diagnostic_code(d) -> String
    diagnostic_spans(d) -> Vector{Any}
    primary_span_label(d) -> String

Field accessors for a diagnostic object, each total: a field rustc did not emit
reads as empty. Written out rather than indexed at the call site so that the
shape of rustc's JSON is described in one place.
"""
function diagnostic_level(d::AbstractDict)
    level = get(d, "level", "")
    return level isa String ? level : ""
end

function diagnostic_code(d::AbstractDict)
    code = get(d, "code", nothing)
    code isa AbstractDict || return ""
    value = get(code, "code", "")
    return value isa String ? value : ""
end

function diagnostic_spans(d::AbstractDict)
    spans = get(d, "spans", nothing)
    return spans isa AbstractVector ? spans : Any[]
end

function primary_span_label(d::AbstractDict)
    for span in diagnostic_spans(d)
        span isa AbstractDict || continue
        get(span, "is_primary", false) === true || continue
        label = get(span, "label", "")
        label isa String && !isempty(label) && return label
    end
    return ""
end
