# Rust struct descriptions and Julia-side wrapper emission.
#
# `RustStructInfo` / `RustMethod` are populated from the FFI manifest produced by
# `rustcall-extract` (see `src/manifest.jl`). The Rust-side `extern "C"` wrappers
# for inline structs are generated by the extractor's `expand` command; this file
# only emits the Julia definitions that call them.

"""
    RustMethod

A method of a `#[julia]` struct as recorded in the manifest.

- `symbol`: exported wrapper symbol (`rustcall_<Struct>_<method>`, #279); empty
  for generic structs, and for a method built by hand rather than read from a
  manifest, where the emitters fall back to `method_wrapper_symbol`
- `is_constructor`: static `new`, or any method returning `Self`/the struct type
- `returns_boxed_struct`: the wrapper boxes the result and returns `*mut Struct`
  (manifest `Method.returns_boxed_struct`, schema 4). Julia used to re-derive
  this by comparing `return_type` against `"Self"` (#276)
- `generic_wrapper`: generic wrapper source registered for monomorphization
"""
struct RustMethod
    name::String
    is_static::Bool        # true if no 'self'
    is_mutable::Bool       # true if '&mut self'
    arg_names::Vector{String}
    arg_types::Vector{String}
    return_type::String
    symbol::String
    is_constructor::Bool
    generic_wrapper::String
    arg_abis::Vector{String}   # manifest `abi` per argument ("string", "str" or "")
    return_abi::String         # "string" (owned buffer), "str" (borrowed) or ""
    returns_boxed_struct::Bool
end

function RustMethod(name::String, is_static::Bool, is_mutable::Bool, arg_names::Vector{String},
                    arg_types::Vector{String}, return_type::String;
                    symbol::String = "", is_constructor::Bool = (name == "new" || return_type == "Self"),
                    generic_wrapper::String = "",
                    arg_abis::Vector{String} = _default_arg_abis(arg_types),
                    return_abi::String = _default_return_abi(return_type, arg_abis),
                    returns_boxed_struct::Bool = is_constructor)
    RustMethod(name, is_static, is_mutable, arg_names, arg_types, return_type,
               symbol, is_constructor, generic_wrapper, arg_abis, return_abi,
               returns_boxed_struct)
end

"""
    method_wrapper_symbol(struct_name, method::RustMethod) -> String

The exported symbol the Julia wrapper of a **concrete** struct method calls.

Manifest-backed methods carry it in `symbol` (`rustcall_<Struct>_<method>`
since #279). The six-argument `RustMethod` constructor cannot know the struct
name, so a hand-built method records none; rather than emit `_get_func_ptr("")`
the symbol is derived from the same scheme here. Generic structs never take
this path: their wrappers are monomorphized by name and are addressed through
`generic_wrapper`, not through a symbol.
"""
function method_wrapper_symbol(struct_name::AbstractString, method::RustMethod)
    isempty(method.symbol) || return method.symbol
    return ffi_method_symbol(struct_name, method.name)
end

"""
    _default_return_abi(return_type, arg_abis) -> String

The `return_abi` for methods constructed by hand: a `String` return is an
owned buffer, a `&str` return is borrowed unless the method also takes string
arguments, in which case the wrapper copies it (see
`rustcall_core::codegen::return_abi`).
"""
function _default_return_abi(return_type::AbstractString, arg_abis)
    rt = strip(return_type)
    rt == "String" && return "string"
    rt == "&str" && return any(_is_string_abi, arg_abis) ? "string" : "str"
    return ""
end

"""
    RustStructInfo

A `#[julia]` / `#[derive(JuliaStruct)]` struct as recorded in the manifest.

- `fields`: `(name, rust_type)` for every named field
- `field_abis`: manifest `Field.abi` per field — `"string"` when the getter
  returns an owned `<Struct>_RustCallOwnedString` buffer, `""` when it returns
  the field as written (schema 4, #276). Absent keys mean `""`
- `field_getters` / `field_setters`: exported accessor symbols per accessible field
- `context_code`: struct + impl source (generic structs only)
- `generic_wrappers`: `(name, source, type_params)` wrappers registered for monomorphization;
  `type_params` are the wrapper's own parameter names in the struct's parameter order
  (`impl<U> Wrapper<U>` wrappers list `U` where the struct declares `T`)
- `has_owned_string_helper` / `has_borrowed_string_helper`: whether the
  `<Struct>_RustCallOwnedString` / `<Struct>_RustCallBorrowedString` ABI helpers exist
"""
struct RustStructInfo
    name::String
    type_params::Vector{String}
    methods::Vector{RustMethod}
    context_code::String
    fields::Vector{Tuple{String, String}}
    field_abis::Dict{String, String}
    has_derive_julia_struct::Bool
    derive_options::Dict{String, Bool}
    field_getters::Dict{String, String}
    field_setters::Dict{String, String}
    has_clone::Bool
    has_owned_string_helper::Bool
    has_borrowed_string_helper::Bool
    generic_wrappers::Vector{Tuple{String, String, Vector{String}}}
    constraints::Dict{Symbol, TypeConstraints}
    module_path::Vector{String}
end

function RustStructInfo(name::String, type_params::Vector{String}, methods::Vector{RustMethod},
                        context_code::String, fields::Vector{Tuple{String, String}},
                        has_derive_julia_struct::Bool, derive_options::Dict{String, Bool};
                        field_abis::Dict{String, String} = Dict{String, String}(),
                        field_getters::Dict{String, String} = Dict{String, String}(),
                        field_setters::Dict{String, String} = Dict{String, String}(),
                        has_clone::Bool = get(derive_options, "Clone", false),
                        has_owned_string_helper::Bool = false,
                        has_borrowed_string_helper::Bool = false,
                        generic_wrappers::Vector{Tuple{String, String, Vector{String}}} = Tuple{String, String, Vector{String}}[],
                        constraints::Dict{Symbol, TypeConstraints} = Dict{Symbol, TypeConstraints}(),
                        module_path::Vector{String} = String[])
    RustStructInfo(name, type_params, methods, context_code, fields, field_abis,
                   has_derive_julia_struct,
                   derive_options, field_getters, field_setters, has_clone,
                   has_owned_string_helper, has_borrowed_string_helper, generic_wrappers, constraints,
                   module_path)
end

"""
    field_is_accessible(info::RustStructInfo, field_name) -> Bool

Whether the manifest recorded an exported getter for the field.
"""
field_is_accessible(info::RustStructInfo, field_name::AbstractString) = haskey(info.field_getters, String(field_name))

"""
    register_generic_struct_wrappers(info::RustStructInfo, expanded_source::String)

Register the generic wrapper functions of a generic `#[julia]` struct for
on-demand monomorphization. The extractor emits the (unexported) generic
wrappers into the expanded source next to the struct, so the registered code
is the whole expanded block and each wrapper is addressed by its qualified
name (`module::Struct_method`); `specialize` then instantiates it in place with
every module-scoped name available. Non-generic structs have their wrappers
compiled into the library directly and need no registration.
"""
function register_generic_struct_wrappers(info::RustStructInfo, expanded_source::String; compiler = nothing)
    isempty(info.type_params) && return nothing
    for (wrapper_name, _, wrapper_params) in info.generic_wrappers
        # The wrapper's own parameter names, positionally aligned with the
        # struct's parameters, so `Point{Int32}` binds the right name even when
        # the impl block renames them (`impl<U> Point<U>`).
        type_params = isempty(wrapper_params) ? Symbol.(info.type_params) : Symbol.(wrapper_params)
        constraints = Dict{Symbol, TypeConstraints}()
        for (sp, wp) in zip(Symbol.(info.type_params), type_params)
            haskey(info.constraints, sp) && (constraints[wp] = info.constraints[sp])
        end
        m = findfirst(mm -> "$(info.name)_$(mm.name)" == wrapper_name, info.methods)
        arg_types = m === nothing ? String[] : info.methods[m].arg_types
        register_generic_function(wrapper_name, expanded_source, type_params, constraints, "";
                                  arg_types = arg_types,
                                  path = qualified_name(info.module_path, wrapper_name), compiler)
    end
    return nothing
end

"""
    emit_julia_definitions(info::RustStructInfo)

Generate Julia code to define a corresponding mutable struct and its methods.
Only generates definitions for structs marked with #[derive(JuliaStruct)] or #[julia].
"""
function emit_julia_definitions(info::RustStructInfo)
    # Only generate Julia definitions for structs with #[derive(JuliaStruct)]
    # This is set when #[julia] attribute is used (transformed to #[derive(JuliaStruct)])
    if !info.has_derive_julia_struct
        return :()  # Return empty expression - no Julia wrapper generated
    end

    struct_name_str = info.name
    esc_struct = esc(Symbol(struct_name_str))

    # Handle Generics
    if !isempty(info.type_params)
        # struct Point{T}
        T_params = [Symbol(t) for t in info.type_params]
        esc_T_params = [esc(t) for t in T_params]
        where_clause = :($(esc_struct){$(esc_T_params...)})

        exprs = []

        # 1. Define Struct
        # The destructor of a *generic* struct is itself generic, so the
        # instantiation has to be compiled before the finalizer needs it —
        # monomorphizing from inside a finalizer would run the extractor and
        # rustc and take REGISTRY_LOCK.
        # `generic_struct_generation_snapshot` does the instantiation here and
        # hands back the pointer *and* the liveness flag of the image that
        # exports it, which the object carries (#249, #277).
        generic_free_name = ffi_struct_free_symbol(struct_name_str)
        push!(exprs, quote
            mutable struct $where_clause
                ptr::Ptr{Cvoid}
                lib_name::String
                # Captured at construction so the finalizer needs no lookup:
                # the destructor, and the flag that says whether the library
                # that owns it is still loaded.
                free_ptr::Ptr{Cvoid}
                alive::Base.RefValue{Bool}

                function $where_clause(ptr::Ptr{Cvoid}, lib::String) where {$(esc_T_params...)}
                    # One snapshot, exactly as the non-generic path takes one:
                    # the instantiated destructor and the liveness flag of the
                    # image that exports it. Taken separately, an unload
                    # between them handed the object a destructor from the
                    # retired image and a *freshly invented* live flag, so it
                    # never learned that image had closed (#249, #277).
                    gen = RustCall.generic_struct_generation_snapshot(
                        $generic_free_name, ($(esc_T_params...),), lib)
                    obj = new{$(esc_T_params...)}(ptr, lib, gen.free_ptr, gen.alive)
                    finalizer(RustCall.finalize_rust_object!, obj)
                    return obj
                end
            end
        end)

        # 2. Methods
        for m in info.methods
            fname = esc(Symbol(m.name))
            wrapper_name = "$(struct_name_str)_$(m.name)"
            is_ctor = m.is_constructor

            arg_names = [Symbol(an) for an in m.arg_names]
            esc_args = [esc(a) for a in arg_names]

            if m.is_static
                 if is_ctor
                     # Point(x, y) -> Point{T}(ptr, lib)
                     # Needs to infer T? Or explicit?
                     # For simplicity, we define: function Point{T}(args...)
                     push!(exprs, quote
                         function (::Type{$esc_struct})($(esc_args...))
                             # Infer T from args? Or assume args are T?
                             # This is tricky without explicit types.
                             # We assume simpler case: Point{Int32}(1, 2)
                             error("Automatic constructor for generic structs is not yet fully implemented. Use explicit builder pattern.")
                         end

                         function (::Type{$where_clause})($(esc_args...)) where {$(esc_T_params...)}
                             # The destructor is compiled and *captured* by the
                             # inner constructor below (`generic_struct_generation_snapshot`),
                             # which is strictly stronger than warming it up:
                             # the finalizer holds the pointer and consults no
                             # registry at all (#249).

                             # Call generic constructor
                             # Point_new<T>(...)
                             # Pass args and types as tuples to separate them
                             ptr_lib_tuple = _call_generic_constructor($wrapper_name, ($(esc_args...),), ($(esc_T_params...),))

                             (ptr_val, lib_val) = ptr_lib_tuple
                             return $esc_struct{$(esc_T_params...)}(ptr_val, lib_val)
                         end
                     end)
                 end
            else
                 # `self` stays alive for the whole call: a borrowed `&str`
                 # result points into the Rust object (#242 review).
                 push!(exprs, quote
                     function $fname(self::$where_clause, $(esc_args...)) where {$(esc_T_params...)}
                         GC.@preserve self begin
                             _call_generic_method(self.lib_name, $wrapper_name, self.ptr, ($(esc_args...),), ($(esc_T_params...),))
                         end
                     end
                 end)
            end
        end

        # 3. Field and Method Accessors
        field_getters = Dict{Symbol, Tuple{String, String}}()
        field_setters = Dict{Symbol, String}()
        if info.has_derive_julia_struct && !isempty(info.fields)
            for (field_name, field_type) in info.fields
                field_is_accessible(info, field_name) || continue
                field_sym = Symbol(field_name)
                field_getters[field_sym] = (info.field_getters[field_name], field_type)
                if haskey(info.field_setters, field_name)
                    field_setters[field_sym] = info.field_setters[field_name]
                end
            end
        end

        method_names = Set([Symbol(m.name) for m in info.methods])
        method_accessors = Expr[]
        for m in info.methods
            method_sym = Symbol(m.name)
            method_func = esc(Symbol(m.name))
            push!(method_accessors, quote
                if field === $(QuoteNode(method_sym))
                    return (args...) -> $method_func(self, args...)
                end
            end)
        end

        push!(exprs, quote
            function Base.getproperty(self::$where_clause, field::Symbol) where {$(esc_T_params...)}
                field_info = $(QuoteNode(field_getters))
                method_names_set = $(QuoteNode(method_names))

                if haskey(field_info, field)
                    # Reading a field of a finalized object would dereference
                    # C_NULL inside Rust — a segfault instead of an error (#249).
                    RustCall.check_not_freed(self, $struct_name_str)
                    getter_name, rust_field_type = field_info[field]
                    type_param_names = ($(map(name -> QuoteNode(name), info.type_params)...),)
                    field_type = _resolve_generic_struct_field_type(rust_field_type, type_param_names, ($(esc_T_params...),))
                    return _call_generic_field(self.lib_name, getter_name, self.ptr, field_type, ($(esc_T_params...),))
                elseif field in method_names_set
                    $(method_accessors...)
                    return getfield(self, field)
                else
                    return getfield(self, field)
                end
            end

            function Base.setproperty!(self::$where_clause, field::Symbol, value) where {$(esc_T_params...)}
                field_setters_map = $(QuoteNode(field_setters))
                if haskey(field_setters_map, field)
                    RustCall.check_not_freed(self, $struct_name_str)
                    setter_name = field_setters_map[field]
                    _call_generic_method(self.lib_name, setter_name, self.ptr, (value,), ($(esc_T_params...),))
                    return value
                else
                    return setfield!(self, field, value)
                end
            end
        end)

        return Expr(:block, exprs...)
    end

    # Non-Generic Path (Original)
    exprs = []

    # 1. Define the struct
    # The finalizer frees, as `@rust_crate` structs have always done. It used
    # to be disabled with a "diagnose segfault" comment, so an inline
    # `#[julia]` struct leaked its Rust allocation while the same construct
    # from a crate did not — opposite lifetime semantics for one user-visible
    # thing (#249). What makes the free safe is the capture below: the
    # destructor pointer and the library's liveness flag are resolved *now*, so
    # `finalize_rust_object!` takes no lock, looks nothing up and compiles no
    # method.
    push!(exprs, quote
        mutable struct $esc_struct
            ptr::Ptr{Cvoid}
            lib_name::String
            free_ptr::Ptr{Cvoid}
            alive::Base.RefValue{Bool}

            function $esc_struct(ptr::Ptr{Cvoid}, lib::String)
                # One snapshot: the destructor and the liveness flag of the
                # *same* generation. Two lookups could straddle a reload
                # (#249, #277).
                gen = RustCall.artifact_generation_snapshot(lib, $struct_name_str)
                obj = new(ptr, lib, gen.free_ptr, gen.alive)
                finalizer(RustCall.finalize_rust_object!, obj)
                return obj
            end
        end
    end)

    # 2. Add constructors and methods
    for m in info.methods
        fname = esc(Symbol(m.name))
        # Exported symbol of the method wrapper, `rustcall_<Struct>_<method>`
        # (#279); derived when a hand-built `RustMethod` carries none.
        wrapper_name = method_wrapper_symbol(struct_name_str, m)

        is_ctor = m.is_constructor

        arg_names = [Symbol(an) for an in m.arg_names]
        esc_args = [esc(a) for a in arg_names]

        # String arguments become (ptr, len) pairs of temporaries kept alive
        # with GC.@preserve (see `_string_arg_plan`); the temporaries are
        # hygienic here, the user's arguments are escaped. `self` is preserved
        # as well: a borrowed `&str` result points into the Rust object.
        bindings, preserved, expanded_call_args = _string_arg_plan(m, esc)

        if m.is_static
            if is_ctor
                push!(exprs, quote
                    function (::Type{$esc_struct})($(esc_args...))
                        $(bindings...)
                        lib = get_current_library()
                        ptr = GC.@preserve $(preserved...) _call_rust_constructor(lib, $wrapper_name, $(expanded_call_args...))
                        return $esc_struct(ptr, lib)
                    end
                end)
            else
                mc = ffi_return_contract(m.return_type; abi = m.return_abi,
                                         owner = struct_name_str)
                if ffi_owned_string_return(mc)
                    free_fn = mc.free_symbol
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            $(bindings...)
                            lib = get_current_library()
                            return GC.@preserve $(preserved...) _call_rust_owned_string(lib, $wrapper_name, $free_fn, $(expanded_call_args...))
                        end
                    end)
                elseif ffi_borrowed_string_return(mc)
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            $(bindings...)
                            lib = get_current_library()
                            return GC.@preserve $(preserved...) _call_rust_borrowed_string(lib, $wrapper_name, $(expanded_call_args...))
                        end
                    end)
                else
                    # The concrete `Type` is resolved here, at macro-expansion
                    # time, and spliced into the call — no Symbol travels to
                    # run time to be re-resolved through a second table (#276).
                    jl_ret_type = ffi_return_type_or_throw(m.return_type, m.return_abi,
                                                           _ffi_context(m, struct_name_str))
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            $(bindings...)
                            lib = get_current_library()
                            return GC.@preserve $(preserved...) _call_rust_method(lib, $wrapper_name, C_NULL, $jl_ret_type, $(expanded_call_args...))
                        end
                    end)
                end
            end
        else
            mc = ffi_return_contract(m.return_type; abi = m.return_abi, owner = struct_name_str)
            if ffi_owned_string_return(mc)
                free_fn = mc.free_symbol
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        $(bindings...)
                        return GC.@preserve self $(preserved...) _call_rust_owned_string(self.lib_name, $wrapper_name, $free_fn, self.ptr, $(expanded_call_args...))
                    end
                end)
            elseif ffi_borrowed_string_return(mc)
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        $(bindings...)
                        return GC.@preserve self $(preserved...) _call_rust_borrowed_string(self.lib_name, $wrapper_name, self.ptr, $(expanded_call_args...))
                    end
                end)
            else
                jl_ret_type = ffi_return_type_or_throw(m.return_type, m.return_abi,
                                                       _ffi_context(m, struct_name_str))
                # The manifest says whether the wrapper boxes the result
                # (`Method.returns_boxed_struct`, schema 4); Julia no longer
                # re-derives it by comparing the spelling against "Self".
                is_ctor_ret = m.returns_boxed_struct
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        $(bindings...)
                        res = GC.@preserve self $(preserved...) _call_rust_method(self.lib_name, $wrapper_name, self.ptr, $jl_ret_type, $(expanded_call_args...))
                        if $is_ctor_ret
                            return $esc_struct(res, self.lib_name)
                        else
                            return res
                        end
                    end
                end)
            end
        end
    end

    # 3. Add field accessors if derive(JuliaStruct) is present
    if info.has_derive_julia_struct && !isempty(info.fields)
        # Build field accessor mappings
        # `(getter symbol, how to read it, free symbol, C slot type)`. The
        # read kind and the free symbol come from the contract, so nothing here
        # re-derives them from the Rust spelling at run time (#246, #249).
        field_getters = Dict{Symbol, Tuple{String, Symbol, String, Type}}()
        field_setters = Dict{Symbol, String}()

        for (field_name, field_type) in info.fields
            field_is_accessible(info, field_name) || continue
            field_sym = Symbol(field_name)
            c = _ffi_field_return(info, field_name, field_type)
            kind = ffi_owned_string_return(c) ? :owned_string :
                   ffi_borrowed_string_return(c) ? :borrowed_string : :plain
            julia_type = kind === :plain ?
                ffi_return_type_or_throw(field_type, get(info.field_abis, field_name, ""),
                                         _ffi_field_context(info, field_name, field_type)) :
                Any
            free_symbol = c.free_symbol === nothing ? "" : c.free_symbol
            field_getters[field_sym] = (info.field_getters[field_name], kind, free_symbol,
                                        julia_type)
            if haskey(info.field_setters, field_name)
                field_setters[field_sym] = info.field_setters[field_name]
            end
        end

        # Single Base.getproperty for all fields and methods
        method_names = Set([Symbol(m.name) for m in info.methods])
        # Build method accessor expressions
        method_accessors = Expr[]
        for m in info.methods
            method_sym = Symbol(m.name)
            method_func = esc(Symbol(m.name))
            # Use a fixed name 'args' – it's safe within the anonymous function scope
            # and avoids 'Module.##gensym' qualification issues
            push!(method_accessors, quote
                if field === $(QuoteNode(method_sym))
                    return (args...) -> $method_func(self, args...)
                end
            end)
        end

        push!(exprs, quote
            function Base.getproperty(self::$esc_struct, field::Symbol)
                field_info = $(QuoteNode(field_getters))
                method_names_set = $(QuoteNode(method_names))

                # Check if it's a field
                if haskey(field_info, field)
                    RustCall.check_not_freed(self, $struct_name_str)
                    getter_name, read_kind, free_symbol, field_type = field_info[field]
                    lib = self.lib_name
                    if read_kind === :owned_string
                        return GC.@preserve self _call_rust_owned_string(lib, getter_name, free_symbol, self.ptr)
                    elseif read_kind === :borrowed_string
                        return GC.@preserve self _call_rust_borrowed_string(lib, getter_name, self.ptr)
                    else
                        # One snapshot, and the accessor is inside the panic
                        # boundary like every other call (#244, #277).
                        target = RustCall.resolve_call_target(lib, getter_name)
                        return RustCall.guard_rust_panic_ptr(
                            GC.@preserve(self,
                                call_rust_function(target.func_ptr, field_type, self.ptr)),
                            target.channel, getter_name)
                    end
                # Check if it's a method
                elseif field in method_names_set
                    $(method_accessors...)
                    return getfield(self, field)
                else
                    return getfield(self, field)
                end
            end
        end)

        # Single Base.setproperty! for all fields
        push!(exprs, quote
            function Base.setproperty!(self::$esc_struct, field::Symbol, value)
                field_setters_map = $(QuoteNode(field_setters))
                if haskey(field_setters_map, field)
                    RustCall.check_not_freed(self, $struct_name_str)
                    setter_name = field_setters_map[field]
                    lib = self.lib_name
                    target = RustCall.resolve_call_target(lib, setter_name)
                    RustCall.guard_rust_panic_ptr(
                        GC.@preserve(self,
                            call_rust_function(target.func_ptr, Cvoid, self.ptr, value)),
                        target.channel, setter_name)
                    return value
                else
                    return setfield!(self, field, value)
                end
            end
        end)
    end

    # 4. Add trait implementations if requested
    if info.has_derive_julia_struct
        if info.has_clone
            clone_name = struct_name_str * "_clone"
            push!(exprs, quote
                function Base.copy(self::$esc_struct)
                    lib = self.lib_name
                    ptr = _call_rust_constructor(lib, $clone_name, self.ptr)
                    return $esc_struct(ptr, lib)
                end
            end)
        end
    end

    return Expr(:block, exprs...)
end

# ============================================================================
# Finalizers (#249, #277 Phase B4)
#
# A finalizer runs at an arbitrary point, on an arbitrary thread, possibly
# while the running thread already holds `REGISTRY_LOCK`. It must therefore
# take no lock, do no registry lookup, resolve no symbol and compile no method
# — every one of those is a deadlock or a crash waiting for the wrong moment,
# and it is why the inline-struct free was disabled with a "diagnose segfault"
# comment for as long as it was.
#
# So everything a finalizer needs is captured at *construction* time: the
# destructor pointer, and the `Ref{Bool}` that says whether the library is
# still loaded. The finalizer then does four loads, one comparison each, and
# one `ccall`.
# ============================================================================

"""
    FINALIZER_FREE_FAILURES

Number of destructor calls that raised inside a finalizer, process-wide.

A finalizer must not log: `@warn` allocates, can yield, and runs at a moment
the program did not choose. Counting is allocation-free and lock-free, and
`finalizer_failure_count()` makes the number observable to a test or a user
who suspects a leak.
"""
const FINALIZER_FREE_FAILURES = Threads.Atomic{Int}(0)

"""
    finalizer_failure_count() -> Int

How many times a Rust destructor raised while being called from a finalizer.
Non-zero means objects were leaked; the usual cause is a library unloaded
without `unload_library` (which retires its objects properly).
"""
finalizer_failure_count() = FINALIZER_FREE_FAILURES[]

"""
    struct_free_pointer(lib_name, struct_name) -> Ptr{Cvoid}

The destructor of `struct_name` in `lib_name`, resolved **now** so the
finalizer never has to.

Resolved on **that library's own handle**, never through the cross-library
fallback search `get_function_pointer` performs. An allocation made by one
library must be released by the same library — each `cdylib` links its own
allocator shim — so borrowing another library's `<Struct>_free` because this
one happens not to export it would be undefined behaviour dressed up as a
convenience (the allocator contract in `docs/src/panics.md`).

`C_NULL` when the library does not export one — a struct whose destructor was
`#[cfg]`-ed out, or a hand-registered `RustStructInfo` with no library behind
it. A null destructor means the finalizer does nothing, which leaks rather than
crashes: the right trade for a lookup that has already failed.
"""
function struct_free_pointer(lib_name::AbstractString, struct_name::AbstractString)
    return artifact_generation_snapshot(lib_name, struct_name).free_ptr
end

"""
    artifact_generation_snapshot(lib_name, struct_name) -> ArtifactGeneration

The destructor of `struct_name` **and** the liveness flag of the image that
exports it, from one generation, under one lock.

This is what a `#[julia]` struct captures at construction so its finalizer
needs no lookup (#249). The two must come from the same generation: taken
separately, an object could capture the destructor of the image that allocated
it and the liveness flag of the image that replaced it, and would then either
skip a free it should have made or make one into an image that had been closed.

The destructor is resolved on **that library's own handle**, never through the
cross-library fallback: each `cdylib` links its own allocator shim, so
borrowing another library's `<Struct>_free` is undefined behaviour dressed up
as a convenience (the allocator contract in `docs/src/panics.md`).

A missing destructor is `C_NULL`, which makes the finalizer a no-op: a leak
rather than a free through the wrong allocator.
"""
function artifact_generation_snapshot(lib_name::AbstractString,
                                      struct_name::AbstractString)
    name = String(lib_name)
    symbol = ffi_struct_free_symbol(struct_name)
    return lock(REGISTRY_LOCK) do
        alive = get!(() -> Ref(true), ARTIFACT_ALIVE, name)
        generation = get(ARTIFACT_GENERATIONS, name, 0)
        entry = get(RUST_LIBRARIES, name, nothing)
        entry === nothing && return ArtifactGeneration(C_NULL, C_NULL, alive, generation)
        handle, cache = entry
        free_ptr = get(cache, symbol, C_NULL)
        if free_ptr == C_NULL
            found = try
                Libdl.dlsym(handle, symbol; throw_error = false)
            catch e
                @debug "Could not resolve $(symbol) in $(name)" exception = e
                nothing
            end
            if !(found === nothing || found == C_NULL)
                free_ptr = found
                cache[symbol] = found
            end
        end
        return ArtifactGeneration(handle, free_ptr, alive, generation)
    end
end

"""
    finalize_rust_object!(x)

The body every generated `#[julia]` struct finalizer runs.

The order is the contract:

1. read the pointer; a null one means this object was already finalized, or was
   never given one, so there is nothing to do;
2. **null the field before the call**, so a second finalization — or a
   concurrent one — cannot free the same allocation twice;
3. bail out if the library is gone: `unload_artifact!` flipped the captured
   liveness flag, and calling into a `dlclose`d image is a jump into freed
   text, which is worse than the leak;
4. call the captured destructor, counting rather than logging a failure.

No lock, no lookup, no allocation on the success path.
"""
function finalize_rust_object!(x)
    ptr = getfield(x, :ptr)
    ptr == C_NULL && return nothing
    setfield!(x, :ptr, C_NULL)
    getfield(x, :alive)[] || return nothing
    free_ptr = getfield(x, :free_ptr)
    free_ptr == C_NULL && return nothing
    try
        ccall(free_ptr, Cvoid, (Ptr{Cvoid},), ptr)
    catch
        Threads.atomic_add!(FINALIZER_FREE_FAILURES, 1)
    end
    return nothing
end

"""
    _generic_struct_free_target(free_name, types) -> (free_ptr, lib_name, handle, generation)

The destructor of one instantiation of a generic `#[julia]` struct, resolved by
monomorphizing it **at construction time**, together with the image it came
from.

This is what `_precompile_generic_free` was reaching for: the specialization
has to be compiled before the finalizer needs it, because monomorphizing from
inside a finalizer would shell out to the extractor, invoke `rustc`, and take
`REGISTRY_LOCK`. Here the pointer is not merely warmed up but captured, so the
finalizer never consults a registry at all.

Not called directly by generated code: `generic_struct_generation_snapshot`
pairs the pointer with the liveness flag of `handle` under one lock, which is
the value a constructor may capture.

`(C_NULL, "", C_NULL, 0)` when the generic destructor is not registered — a
struct whose `_free` wrapper the extractor did not emit.
"""
function _generic_struct_free_target(free_name::AbstractString, types::Tuple)
    return try
        generic_info = lock(REGISTRY_LOCK) do
            get(GENERIC_FUNCTION_REGISTRY, String(free_name), nothing)
        end
        generic_info === nothing && return (C_NULL, "", C_NULL, 0)
        type_params = Dict{Symbol, Type}()
        for (i, p) in enumerate(generic_info.type_params)
            type_params[p] = types[i]
        end
        info = get_monomorphized_function(String(free_name), type_params)
        info === nothing && (info = monomorphize_function(String(free_name), type_params))
        (info.func_ptr, info.lib_name, info.handle, info.generation)
    catch e
        @debug "Could not resolve the destructor of $(free_name)" exception = e
        (C_NULL, "", C_NULL, 0)
    end
end

"""
    generic_struct_generation_snapshot(free_name, types, fallback_lib) -> ArtifactGeneration

The generic counterpart of `artifact_generation_snapshot`: the instantiated
destructor of a generic `#[julia]` struct **and** the liveness flag of the image
that exports it, as one value.

Monomorphizing can run the extractor and `rustc`, so it happens first and
outside the lock. What matters is that the flag is then found **by the handle
the pointer came from** (`alive_ref_for_handle`), not by the library's name: if
that image has since been retired the object gets the retired image's own flag —
which is flipped when the image is closed, which is exactly when the destructor
stops being callable — and if it is gone entirely the object goes inert and
leaks rather than calling into unmapped memory.
"""
function generic_struct_generation_snapshot(free_name::AbstractString, types::Tuple,
                                            fallback_lib::AbstractString)
    free_ptr, free_lib, handle, generation = _generic_struct_free_target(free_name, types)
    name = isempty(free_lib) ? String(fallback_lib) : free_lib
    return lock(REGISTRY_LOCK) do
        free_ptr == C_NULL &&
            return ArtifactGeneration(C_NULL, C_NULL, DEAD_ARTIFACT, generation)
        return ArtifactGeneration(handle, free_ptr, alive_ref_for_handle(handle, name),
                                  generation)
    end
end

"""
    check_not_freed(obj, type_name)

Raise when a method is called on an object whose finalizer already ran.

Without it the call dereferences `C_NULL` inside Rust, which is a segfault
rather than an error message. The inline structs got this in #277 Phase B4;
`@rust_crate` structs have had it since #246 (`_check_not_freed`).
"""
function check_not_freed(obj, type_name::AbstractString)
    if getfield(obj, :ptr) == C_NULL
        throw(RustError("attempted to use a freed $(type_name) object: its " *
                        "finalizer has already released the Rust allocation"))
    end
    return nothing
end

# Internal helpers
function _call_rust_free(lib_name::String, func_name::String, ptr::Ptr{Cvoid})
    # This is for non-generic
    try
        _rust_call_typed(lib_name, func_name, Cvoid, ptr)
    catch e
        @debug "Failed to call Rust free function $func_name in $lib_name: $e"
    end
end

function _call_rust_constructor(lib_name::String, func_name::String, args...)
    return _rust_call_typed(lib_name, func_name, Ptr{Cvoid}, args...)
end

function _crust_string_to_julia(raw::CRustString)
    if raw.ptr == C_NULL || raw.len == 0
        return ""
    end

    bytes = Vector{UInt8}(undef, raw.len)
    unsafe_copyto!(pointer(bytes), raw.ptr, raw.len)
    return String(bytes)
end

function _crust_str_to_julia(raw::CRustStr)
    if raw.ptr == C_NULL || raw.len == 0
        return ""
    end

    bytes = Vector{UInt8}(undef, raw.len)
    unsafe_copyto!(pointer(bytes), raw.ptr, raw.len)
    return String(bytes)
end

function _call_rust_owned_string(lib_name::String, func_name::String, free_func_name::String, args...)
    # One snapshot, taken before the call: the wrapper, its panic channel and
    # the function that releases the buffer it returns. The release function
    # used to be resolved by library name *after* the wrapper had returned, so
    # a reload in between released a buffer allocated by the retired image
    # through the replacement's allocator — undefined behaviour, and exactly
    # what the allocator contract forbids (#277).
    target = resolve_call_target(lib_name, func_name; free_symbol = free_func_name)
    func_ptr = target.func_ptr
    channel = target.channel
    raw = call_rust_function(func_ptr, CRustString, args...)
    # A panic returns the empty buffer sentinel, which would decode to `""`.
    # Read the channel before the buffer, so a panicked call raises instead of
    # quietly producing an empty string. Nothing needs freeing on that path:
    # the sentinel owns no allocation.
    check_rust_panic_ptr(channel, func_name)

    try
        return _crust_string_to_julia(raw)
    finally
        if raw.ptr != C_NULL && target.free_ptr != C_NULL
            ccall(target.free_ptr, Cvoid, (Ptr{UInt8}, UInt, UInt), raw.ptr, raw.len, raw.cap)
        end
    end
end

function _call_rust_borrowed_string(lib_name::String, func_name::String, args...)
    target = resolve_call_target(lib_name, func_name)
    func_ptr = target.func_ptr
    channel = target.channel
    raw = call_rust_function(func_ptr, CRustStr, args...)
    check_rust_panic_ptr(channel, func_name)
    return _crust_str_to_julia(raw)
end

# Function-pointer variants for bindings that resolve symbols themselves
# (`@rust_crate` modules).
function _call_rust_owned_string_ptr(func_ptr::Ptr{Cvoid}, free_ptr::Ptr{Cvoid}, args...)
    raw = call_rust_function(func_ptr, CRustString, args...)
    try
        return _crust_string_to_julia(raw)
    finally
        if raw.ptr != C_NULL
            ccall(free_ptr, Cvoid, (Ptr{UInt8}, UInt, UInt), raw.ptr, raw.len, raw.cap)
        end
    end
end

function _call_rust_borrowed_string_ptr(func_ptr::Ptr{Cvoid}, args...)
    raw = call_rust_function(func_ptr, CRustStr, args...)
    return _crust_str_to_julia(raw)
end

# The return type is a concrete `Type` spliced by the generator, not a Symbol
# resolved here: the second lookup was a nine-entry table that turned every
# small integer into `Any` (#276).
function _call_rust_method(lib_name::String, func_name::String, ptr::Ptr{Cvoid},
                           ret_type::Type, args...)
    if ptr == C_NULL
        return _rust_call_typed(lib_name, func_name, ret_type, args...)
    else
        return _rust_call_typed(lib_name, func_name, ret_type, ptr, args...)
    end
end

# Generic helpers
function _call_generic_constructor(func_name::String, args::Tuple, types::Tuple)
    # Use explicit types to monomorphize
    # We assume types correspond to T, U... in order
    # We need parameter names (T, U).
    # Helper to get parameter names from registry?
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)

    # `_call_monomorphized` applies the string ABI of the specialized wrapper
    # (fixed `String` / `&str` parameters travel as (ptr, len) pairs, #242).
    ptr = _call_monomorphized(info, args...)

    return (ptr, info.lib_name)
end

function _call_generic_method(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, args::Tuple, types::Tuple)
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)

    # Method call: pass ptr (self) then args. The receiver is the wrapper's
    # first parameter, so the string arg plan of `_call_monomorphized` lines
    # up with `args` and a string result is decoded from its buffer.
    return _call_monomorphized(info, ptr, args...)
end

function _call_generic_field(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, ret_type::Type, types::Tuple)
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)
    # A `String` field getter returns an owned buffer (#242); other fields
    # use the type resolved from the struct's parameters.
    info.string_return === :none || return _call_monomorphized(info, ptr)
    return call_rust_function(info.func_ptr, ret_type, ptr)
end

function _resolve_generic_struct_field_type(field_type::String, type_param_names, type_param_values::Tuple)
    stripped = strip(field_type)

    for (name, value) in zip(type_param_names, type_param_values)
        if stripped == String(name)
            return value
        end
    end

    return ffi_return_type_or_throw(stripped, "", "generic field -> $(stripped)")
end

function _precompile_generic_free(func_name::String, types::Tuple)
    # Same as _call_generic_free but only compile/cache
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    # This will cache the function info
    monomorphize_function(func_name, type_params)
end

function _call_generic_free(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, types...)
    # We need to construct the type params manually since we only have types, not values.
    # call_generic_function infers from values.
    # We need explicit monomorphization call.

    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    # Should use cached version (fast path for finalizer)
    info = get_monomorphized_function(func_name, type_params)
    if info === nothing
        # Fallback to monomorphize (unsafe in finalizer)
        # Should not happen if precompiled
        info = monomorphize_function(func_name, type_params)
    end

    call_rust_function(info.func_ptr, Cvoid, ptr)
end

"""
    free_rust_obj(ptr::Ptr{Cvoid}, lib_func::String)

Helper to safely call the Rust destructor.
"""
function free_rust_obj(ptr::Ptr{Cvoid}, lib_func::String)
    if ptr != C_NULL
        # We use @rust here as it handles library lookup automatically
        # Since this is called from the finalizer, we need to be careful.
        # However, @rust is generally thread-safe as it uses a global registry.
        @eval RustCall.@rust $(Symbol(lib_func))(ptr::Ptr{Cvoid})::Cvoid
    end
end
