# Rust struct descriptions and Julia-side wrapper emission.
#
# `RustStructInfo` / `RustMethod` are populated from the FFI manifest produced by
# `rustcall-extract` (see `src/manifest.jl`). The Rust-side `extern "C"` wrappers
# for inline structs are generated by the extractor's `expand` command; this file
# only emits the Julia definitions that call them.

"""
    RustMethod

A method of a `#[julia]` struct as recorded in the manifest.

- `symbol`: exported wrapper symbol (`Struct_method`); empty for generic structs
- `is_constructor`: static `new`, or any method returning `Self`/the struct type
- `generic_wrapper`: generic wrapper source registered for monomorphization
"""
struct RustMethod
    name::String
    is_static::Bool        # true if no 'self'
    is_mutable::Bool       # true if '&mut self'
    arg_names::Vector{String}
    arg_types::Vector{String}
    return_type::String
    symbol::String
    is_constructor::Bool
    generic_wrapper::String
end

function RustMethod(name::String, is_static::Bool, is_mutable::Bool, arg_names::Vector{String},
                    arg_types::Vector{String}, return_type::String;
                    symbol::String = "", is_constructor::Bool = (name == "new" || return_type == "Self"),
                    generic_wrapper::String = "")
    RustMethod(name, is_static, is_mutable, arg_names, arg_types, return_type,
               symbol, is_constructor, generic_wrapper)
end

"""
    RustStructInfo

A `#[julia]` / `#[derive(JuliaStruct)]` struct as recorded in the manifest.

- `fields`: `(name, rust_type)` for every named field
- `field_getters` / `field_setters`: exported accessor symbols per accessible field
- `context_code`: struct + impl source (generic structs only)
- `generic_wrappers`: `(name, source)` wrappers registered for monomorphization
- `has_owned_string_helper` / `has_borrowed_string_helper`: whether the
  `<Struct>_RustCallOwnedString` / `<Struct>_RustCallBorrowedString` ABI helpers exist
"""
struct RustStructInfo
    name::String
    type_params::Vector{String}
    methods::Vector{RustMethod}
    context_code::String
    fields::Vector{Tuple{String, String}}
    has_derive_julia_struct::Bool
    derive_options::Dict{String, Bool}
    field_getters::Dict{String, String}
    field_setters::Dict{String, String}
    has_clone::Bool
    has_owned_string_helper::Bool
    has_borrowed_string_helper::Bool
    generic_wrappers::Vector{Tuple{String, String}}
    constraints::Dict{Symbol, TypeConstraints}
    module_path::Vector{String}
end

function RustStructInfo(name::String, type_params::Vector{String}, methods::Vector{RustMethod},
                        context_code::String, fields::Vector{Tuple{String, String}},
                        has_derive_julia_struct::Bool, derive_options::Dict{String, Bool};
                        field_getters::Dict{String, String} = Dict{String, String}(),
                        field_setters::Dict{String, String} = Dict{String, String}(),
                        has_clone::Bool = get(derive_options, "Clone", false),
                        has_owned_string_helper::Bool = false,
                        has_borrowed_string_helper::Bool = false,
                        generic_wrappers::Vector{Tuple{String, String}} = Tuple{String, String}[],
                        constraints::Dict{Symbol, TypeConstraints} = Dict{Symbol, TypeConstraints}(),
                        module_path::Vector{String} = String[])
    RustStructInfo(name, type_params, methods, context_code, fields, has_derive_julia_struct,
                   derive_options, field_getters, field_setters, has_clone,
                   has_owned_string_helper, has_borrowed_string_helper, generic_wrappers, constraints,
                   module_path)
end

"""
    field_is_accessible(info::RustStructInfo, field_name) -> Bool

Whether the manifest recorded an exported getter for the field.
"""
field_is_accessible(info::RustStructInfo, field_name::AbstractString) = haskey(info.field_getters, String(field_name))

"""
    register_generic_struct_wrappers(info::RustStructInfo, expanded_source::String)

Register the generic wrapper functions of a generic `#[julia]` struct for
on-demand monomorphization. The extractor emits the (unexported) generic
wrappers into the expanded source next to the struct, so the registered code
is the whole expanded block and each wrapper is addressed by its qualified
name (`module::Struct_method`); `specialize` then instantiates it in place with
every module-scoped name available. Non-generic structs have their wrappers
compiled into the library directly and need no registration.
"""
function register_generic_struct_wrappers(info::RustStructInfo, expanded_source::String)
    isempty(info.type_params) && return nothing
    type_params = Symbol.(info.type_params)
    for (wrapper_name, _) in info.generic_wrappers
        m = findfirst(mm -> "$(info.name)_$(mm.name)" == wrapper_name, info.methods)
        arg_types = m === nothing ? String[] : info.methods[m].arg_types
        register_generic_function(wrapper_name, expanded_source, type_params, info.constraints, "";
                                  arg_types = arg_types,
                                  path = qualified_name(info.module_path, wrapper_name))
    end
    return nothing
end

"""
    emit_julia_definitions(info::RustStructInfo)

Generate Julia code to define a corresponding mutable struct and its methods.
Only generates definitions for structs marked with #[derive(JuliaStruct)] or #[julia].
"""
function emit_julia_definitions(info::RustStructInfo)
    # Only generate Julia definitions for structs with #[derive(JuliaStruct)]
    # This is set when #[julia] attribute is used (transformed to #[derive(JuliaStruct)])
    if !info.has_derive_julia_struct
        return :()  # Return empty expression - no Julia wrapper generated
    end

    struct_name_str = info.name
    esc_struct = esc(Symbol(struct_name_str))

    # Handle Generics
    if !isempty(info.type_params)
        # struct Point{T}
        T_params = [Symbol(t) for t in info.type_params]
        esc_T_params = [esc(t) for t in T_params]
        where_clause = :($(esc_struct){$(esc_T_params...)})

        exprs = []

        # 1. Define Struct
        push!(exprs, quote
            mutable struct $where_clause
                ptr::Ptr{Cvoid}
                lib_name::String

                function $where_clause(ptr::Ptr{Cvoid}, lib::String) where {$(esc_T_params...)}
                    obj = new{$(esc_T_params...)}(ptr, lib)
                    finalizer(obj) do x
                        # Temporarily disabled free to diagnose segfault
                        @debug "Finalizer: skipped free for generic struct $(struct_name_str) (ptr=$(x.ptr))"
                        x.ptr = C_NULL
                    end
                    return obj
                end
            end
        end)

        # 2. Methods
        for m in info.methods
            fname = esc(Symbol(m.name))
            wrapper_name = "$(struct_name_str)_$(m.name)"
            is_ctor = m.is_constructor

            arg_names = [Symbol(an) for an in m.arg_names]
            esc_args = [esc(a) for a in arg_names]

            if m.is_static
                 if is_ctor
                     # Point(x, y) -> Point{T}(ptr, lib)
                     # Needs to infer T? Or explicit?
                     # For simplicity, we define: function Point{T}(args...)
                     push!(exprs, quote
                         function (::Type{$esc_struct})($(esc_args...))
                             # Infer T from args? Or assume args are T?
                             # This is tricky without explicit types.
                             # We assume simpler case: Point{Int32}(1, 2)
                             error("Automatic constructor for generic structs is not yet fully implemented. Use explicit builder pattern.")
                         end

                         function (::Type{$where_clause})($(esc_args...)) where {$(esc_T_params...)}
                             # Precompile free function to avoid compilation in finalizer
                             _precompile_generic_free($(struct_name_str * "_free"), ($(esc_T_params...),))

                             # Call generic constructor
                             # Point_new<T>(...)
                             # Pass args and types as tuples to separate them
                             ptr_lib_tuple = _call_generic_constructor($wrapper_name, ($(esc_args...),), ($(esc_T_params...),))

                             (ptr_val, lib_val) = ptr_lib_tuple
                             return $esc_struct{$(esc_T_params...)}(ptr_val, lib_val)
                         end
                     end)
                 end
            else
                 push!(exprs, quote
                     function $fname(self::$where_clause, $(esc_args...)) where {$(esc_T_params...)}
                         _call_generic_method(self.lib_name, $wrapper_name, self.ptr, ($(esc_args...),), ($(esc_T_params...),))
                     end
                 end)
            end
        end

        # 3. Field and Method Accessors
        field_getters = Dict{Symbol, Tuple{String, String}}()
        field_setters = Dict{Symbol, String}()
        if info.has_derive_julia_struct && !isempty(info.fields)
            for (field_name, field_type) in info.fields
                field_is_accessible(info, field_name) || continue
                field_sym = Symbol(field_name)
                field_getters[field_sym] = (info.field_getters[field_name], field_type)
                if haskey(info.field_setters, field_name)
                    field_setters[field_sym] = info.field_setters[field_name]
                end
            end
        end

        method_names = Set([Symbol(m.name) for m in info.methods])
        method_accessors = Expr[]
        for m in info.methods
            method_sym = Symbol(m.name)
            method_func = esc(Symbol(m.name))
            push!(method_accessors, quote
                if field === $(QuoteNode(method_sym))
                    return (args...) -> $method_func(self, args...)
                end
            end)
        end

        push!(exprs, quote
            function Base.getproperty(self::$where_clause, field::Symbol) where {$(esc_T_params...)}
                field_info = $(QuoteNode(field_getters))
                method_names_set = $(QuoteNode(method_names))

                if haskey(field_info, field)
                    getter_name, rust_field_type = field_info[field]
                    type_param_names = ($(map(name -> QuoteNode(name), info.type_params)...),)
                    field_type = _resolve_generic_struct_field_type(rust_field_type, type_param_names, ($(esc_T_params...),))
                    return _call_generic_field(self.lib_name, getter_name, self.ptr, field_type, ($(esc_T_params...),))
                elseif field in method_names_set
                    $(method_accessors...)
                    return getfield(self, field)
                else
                    return getfield(self, field)
                end
            end

            function Base.setproperty!(self::$where_clause, field::Symbol, value) where {$(esc_T_params...)}
                field_setters_map = $(QuoteNode(field_setters))
                if haskey(field_setters_map, field)
                    setter_name = field_setters_map[field]
                    _call_generic_method(self.lib_name, setter_name, self.ptr, (value,), ($(esc_T_params...),))
                    return value
                else
                    return setfield!(self, field, value)
                end
            end
        end)

        return Expr(:block, exprs...)
    end

    # Non-Generic Path (Original)
    exprs = []

    # 1. Define the struct
    push!(exprs, quote
        mutable struct $esc_struct
            ptr::Ptr{Cvoid}
            lib_name::String

            function $esc_struct(ptr::Ptr{Cvoid}, lib::String)
                obj = new(ptr, lib)
                finalizer(obj) do x
                    if x.ptr != C_NULL
                        # Temporarily disabled free to diagnose segfault
                        @debug "Finalizer: skipped free for struct $(struct_name_str) (ptr=$(x.ptr))"
                        x.ptr = C_NULL
                    end
                end
                return obj
            end
        end
    end)

    # 2. Add constructors and methods
    for m in info.methods
        fname = esc(Symbol(m.name))
        wrapper_name = struct_name_str * "_" * m.name

        is_ctor = m.is_constructor

        arg_names = [Symbol(an) for an in m.arg_names]
        esc_args = [esc(a) for a in arg_names]

        # Build expanded arguments for String types
        # String args need to be passed as (pointer, length) pairs
        expanded_call_args = Expr[]
        for (aname, atype) in zip(arg_names, m.arg_types)
            esc_aname = esc(aname)
            if atype == "String" || atype == "&str"
                # Convert to (pointer, length) pair
                push!(expanded_call_args, :(pointer($esc_aname)))
                push!(expanded_call_args, :(sizeof($esc_aname)))
            else
                push!(expanded_call_args, esc_aname)
            end
        end

        if m.is_static
            if is_ctor
                push!(exprs, quote
                    function (::Type{$esc_struct})($(esc_args...))
                        lib = get_current_library()
                        ptr = _call_rust_constructor(lib, $wrapper_name, $(expanded_call_args...))
                        return $esc_struct(ptr, lib)
                    end
                end)
            else
                if m.return_type == "String"
                    free_fn = struct_name_str * "_free_rust_string"
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            lib = get_current_library()
                            return _call_rust_owned_string(lib, $wrapper_name, $free_fn, $(expanded_call_args...))
                        end
                    end)
                elseif m.return_type == "&str"
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            lib = get_current_library()
                            return _call_rust_borrowed_string(lib, $wrapper_name, $(expanded_call_args...))
                        end
                    end)
                else
                    jl_ret_type = rust_to_julia_type_sym(m.return_type)
                    push!(exprs, quote
                        function $fname($(esc_args...))
                            lib = get_current_library()
                            return _call_rust_method(lib, $wrapper_name, C_NULL, $(expanded_call_args...), $(QuoteNode(jl_ret_type)))
                        end
                    end)
                end
            end
        else
            if m.return_type == "String"
                free_fn = struct_name_str * "_free_rust_string"
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        return _call_rust_owned_string(self.lib_name, $wrapper_name, $free_fn, self.ptr, $(expanded_call_args...))
                    end
                end)
            elseif m.return_type == "&str"
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        return _call_rust_borrowed_string(self.lib_name, $wrapper_name, self.ptr, $(expanded_call_args...))
                    end
                end)
            else
                jl_ret_type = rust_to_julia_type_sym(m.return_type)
                is_ctor_ret = m.return_type == "Self" || m.return_type == struct_name_str
                push!(exprs, quote
                    function $fname(self::$esc_struct, $(esc_args...))
                        res = _call_rust_method(self.lib_name, $wrapper_name, self.ptr, $(expanded_call_args...), $(QuoteNode(jl_ret_type)))
                        if $is_ctor_ret
                            return $esc_struct(res, self.lib_name)
                        else
                            return res
                        end
                    end
                end)
            end
        end
    end

    # 3. Add field accessors if derive(JuliaStruct) is present
    if info.has_derive_julia_struct && !isempty(info.fields)
        # Build field accessor mappings
        field_getters = Dict{Symbol, Tuple{String, String}}()
        field_setters = Dict{Symbol, String}()

        for (field_name, field_type) in info.fields
            field_is_accessible(info, field_name) || continue
            field_sym = Symbol(field_name)
            field_getters[field_sym] = (info.field_getters[field_name], field_type)
            if haskey(info.field_setters, field_name)
                field_setters[field_sym] = info.field_setters[field_name]
            end
        end

        # Single Base.getproperty for all fields and methods
        method_names = Set([Symbol(m.name) for m in info.methods])
        # Build method accessor expressions
        method_accessors = Expr[]
        for m in info.methods
            method_sym = Symbol(m.name)
            method_func = esc(Symbol(m.name))
            # Use a fixed name 'args' – it's safe within the anonymous function scope
            # and avoids 'Module.##gensym' qualification issues
            push!(method_accessors, quote
                if field === $(QuoteNode(method_sym))
                    return (args...) -> $method_func(self, args...)
                end
            end)
        end

        push!(exprs, quote
            function Base.getproperty(self::$esc_struct, field::Symbol)
                field_info = $(QuoteNode(field_getters))
                method_names_set = $(QuoteNode(method_names))

                # Check if it's a field
                if haskey(field_info, field)
                    getter_name, rust_field_type = field_info[field]
                    lib = self.lib_name
                    if rust_field_type == "String"
                        return _call_rust_owned_string(lib, getter_name, $(struct_name_str * "_free_rust_string"), self.ptr)
                    elseif rust_field_type == "&str"
                        return _call_rust_borrowed_string(lib, getter_name, self.ptr)
                    else
                        func_ptr = get_function_pointer(lib, getter_name)
                        field_type = julia_sym_to_type(rust_to_julia_type_sym(rust_field_type))
                        return call_rust_function(func_ptr, field_type, self.ptr)
                    end
                # Check if it's a method
                elseif field in method_names_set
                    $(method_accessors...)
                    return getfield(self, field)
                else
                    return getfield(self, field)
                end
            end
        end)

        # Single Base.setproperty! for all fields
        push!(exprs, quote
            function Base.setproperty!(self::$esc_struct, field::Symbol, value)
                field_setters_map = $(QuoteNode(field_setters))
                if haskey(field_setters_map, field)
                    setter_name = field_setters_map[field]
                    lib = self.lib_name
                    func_ptr = get_function_pointer(lib, setter_name)
                    call_rust_function(func_ptr, Cvoid, self.ptr, value)
                    return value
                else
                    return setfield!(self, field, value)
                end
            end
        end)
    end

    # 4. Add trait implementations if requested
    if info.has_derive_julia_struct
        if info.has_clone
            clone_name = struct_name_str * "_clone"
            push!(exprs, quote
                function Base.copy(self::$esc_struct)
                    lib = self.lib_name
                    ptr = _call_rust_constructor(lib, $clone_name, self.ptr)
                    return $esc_struct(ptr, lib)
                end
            end)
        end
    end

    return Expr(:block, exprs...)
end

# Internal helpers
function _call_rust_free(lib_name::String, func_name::String, ptr::Ptr{Cvoid})
    # This is for non-generic
    try
        _rust_call_typed(lib_name, func_name, Cvoid, ptr)
    catch e
        @debug "Failed to call Rust free function $func_name in $lib_name: $e"
    end
end

function _call_rust_constructor(lib_name::String, func_name::String, args...)
    return _rust_call_typed(lib_name, func_name, Ptr{Cvoid}, args...)
end

function _crust_string_to_julia(raw::CRustString)
    if raw.ptr == C_NULL || raw.len == 0
        return ""
    end

    bytes = Vector{UInt8}(undef, raw.len)
    unsafe_copyto!(pointer(bytes), raw.ptr, raw.len)
    return String(bytes)
end

function _crust_str_to_julia(raw::CRustStr)
    if raw.ptr == C_NULL || raw.len == 0
        return ""
    end

    bytes = Vector{UInt8}(undef, raw.len)
    unsafe_copyto!(pointer(bytes), raw.ptr, raw.len)
    return String(bytes)
end

function _call_rust_owned_string(lib_name::String, func_name::String, free_func_name::String, args...)
    func_ptr = get_function_pointer(lib_name, func_name)
    raw = call_rust_function(func_ptr, CRustString, args...)

    try
        return _crust_string_to_julia(raw)
    finally
        if raw.ptr != C_NULL
            free_ptr = get_function_pointer(lib_name, free_func_name)
            ccall(free_ptr, Cvoid, (Ptr{UInt8}, UInt, UInt), raw.ptr, raw.len, raw.cap)
        end
    end
end

function _call_rust_borrowed_string(lib_name::String, func_name::String, args...)
    func_ptr = get_function_pointer(lib_name, func_name)
    raw = call_rust_function(func_ptr, CRustStr, args...)
    return _crust_str_to_julia(raw)
end

function _call_rust_method(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, args...)
    ret_type = last(args)
    actual_args = args[1:end-1]
    real_ret_type = julia_sym_to_type(ret_type)

    if ptr == C_NULL
        return _rust_call_typed(lib_name, func_name, real_ret_type, actual_args...)
    else
        return _rust_call_typed(lib_name, func_name, real_ret_type, ptr, actual_args...)
    end
end

# Generic helpers
function _call_generic_constructor(func_name::String, args::Tuple, types::Tuple)
    # Use explicit types to monomorphize
    # We assume types correspond to T, U... in order
    # We need parameter names (T, U).
    # Helper to get parameter names from registry?
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)

    # args are in a tuple, need to splat
    ptr = call_rust_function(info.func_ptr, info.return_type, args...)

    return (ptr, info.lib_name)
end

function _call_generic_method(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, args::Tuple, types::Tuple)
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)

    # Method call: pass ptr (self) then args
    return call_rust_function(info.func_ptr, info.return_type, ptr, args...)
end

function _call_generic_field(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, ret_type::Type, types::Tuple)
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    info = monomorphize_function(func_name, type_params)
    return call_rust_function(info.func_ptr, ret_type, ptr)
end

function _resolve_generic_struct_field_type(field_type::String, type_param_names, type_param_values::Tuple)
    stripped = strip(field_type)

    for (name, value) in zip(type_param_names, type_param_values)
        if stripped == String(name)
            return value
        end
    end

    return julia_sym_to_type(rust_to_julia_type_sym(stripped))
end

function _precompile_generic_free(func_name::String, types::Tuple)
    # Same as _call_generic_free but only compile/cache
    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    # This will cache the function info
    monomorphize_function(func_name, type_params)
end

function _call_generic_free(lib_name::String, func_name::String, ptr::Ptr{Cvoid}, types...)
    # We need to construct the type params manually since we only have types, not values.
    # call_generic_function infers from values.
    # We need explicit monomorphization call.

    generic_info = GENERIC_FUNCTION_REGISTRY[func_name]
    param_names = generic_info.type_params

    type_params = Dict{Symbol, Type}()
    for (i, p) in enumerate(param_names)
        type_params[p] = types[i]
    end

    # Should use cached version (fast path for finalizer)
    info = get_monomorphized_function(func_name, type_params)
    if info === nothing
        # Fallback to monomorphize (unsafe in finalizer)
        # Should not happen if precompiled
        info = monomorphize_function(func_name, type_params)
    end

    call_rust_function(info.func_ptr, Cvoid, ptr)
end

function julia_sym_to_type(s::Symbol)
    m = Dict(
        :Float64 => Float64,
        :Float32 => Float32,
        :Int32 => Int32,
        :Int64 => Int64,
        :UInt32 => UInt32,
        :UInt64 => UInt64,
        :Bool => Bool,
        :Cvoid => Cvoid,
        :Any => Any
    )
    return get(m, s, Any)
end

"""
    rust_to_julia_type_sym(rust_type::String) -> Symbol

Map Rust type strings to Julia type symbols for code generation.
"""
function rust_to_julia_type_sym(rust_type::String)
    m = Dict(
        "f64" => :Float64,
        "f32" => :Float32,
        "i32" => :Int32,
        "i64" => :Int64,
        "u32" => :UInt32,
        "u64" => :UInt64,
        "bool" => :Bool,
        "()" => :Cvoid,
        "String" => :RustString,
        "&str" => :RustStr,
    )
    return get(m, rust_type, :Any)
end


"""
    free_rust_obj(ptr::Ptr{Cvoid}, lib_func::String)

Helper to safely call the Rust destructor.
"""
function free_rust_obj(ptr::Ptr{Cvoid}, lib_func::String)
    if ptr != C_NULL
        # We use @rust here as it handles library lookup automatically
        # Since this is called from the finalizer, we need to be careful.
        # However, @rust is generally thread-safe as it uses a global registry.
        @eval RustCall.@rust $(Symbol(lib_func))(ptr::Ptr{Cvoid})::Cvoid
    end
end
